import { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { AdminLayout } from '../../components/layout/AdminLayout';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../components/ui/card';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { Textarea } from '../../components/ui/textarea';
import { RichTextEditor } from '../../components/ui/RichTextEditor';
import { ArrowLeft, Save, Eye, BookOpen, Loader2, Image as ImageIcon, HelpCircle, CheckCircle2, XCircle, Plus, X, Calendar, MapPin, Tag } from 'lucide-react';
import { useToast } from '../../contexts/ToastContext';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { cmsApi, Chapter } from '../../services/api/cms';
import { postsApi } from '../../services/api/posts';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '../../components/ui/dialog';

export default function CreateGeneralKnowledgePage() {
  const navigate = useNavigate();
  const { id } = useParams<{ id?: string }>();
  const isEditMode = !!id;
  const { showToast } = useToast();
  const queryClient = useQueryClient();

  // Category and sub-category creation removed - use Wall Categories in dashboard instead
  
  // MCQ Dialog state
  const [isMcqDialogOpen, setIsMcqDialogOpen] = useState(false);
  const [mcqFormData, setMcqFormData] = useState({
    question: '',
    options: ['', '', '', ''],
    correctAnswer: 0,
    categoryId: '',
    explanation: '',
  });
  const [createdMcqs, setCreatedMcqs] = useState<any[]>([]);

  const [formData, setFormData] = useState({
    title: '',
    description: '',
    fullArticle: '',
    category: '',
    subCategory: '',
    subCategoryId: '',
    chapterId: '',
    section: '',
    country: '',
    categoryId: '',
    imageUrl: '',
    imageFile: null as File | null,
    imagePreview: null as string | null,
    // New fields
    postType: 'General Knowledge',
    targetedKeywords: '',
    autoGeneratedKeywords: '',
    date: '', // Event date
    eventDates: [] as string[], // Array of dates for notifications (month-day only)
    eventYearRange: '',
    location: {
      lat: '',
      long: '',
    },
    state: '',
    district: '',
    city: '',
    language: 'ENGLISH', // Language tag: ENGLISH or HINDI
    isPublished: false,
    isActive: true,
    sendNotification: false,
    notificationTime: '', // Clock time for notification
    articleId: '', // For linking MCQ
  });

  // Fetch categories (Wall parent categories)
  const { data: categoriesData } = useQuery({
    queryKey: ['wall-categories'],
    queryFn: () => postsApi.getWallCategories(),
  });

  const categories = categoriesData || [];

  // Fetch sub-categories for the selected category
  const { data: subCategoriesData } = useQuery({
    queryKey: ['wall-subcategories', formData.categoryId],
    queryFn: () =>
      formData.categoryId ? postsApi.getWallSubCategories(formData.categoryId) : [],
    enabled: !!formData.categoryId,
  });

  const subCategories = subCategoriesData || [];

  // Fetch chapters for the selected sub-category
  const { data: chaptersData } = useQuery<Chapter[]>({
    queryKey: ['chapters', formData.subCategoryId],
    queryFn: () =>
      formData.subCategoryId ? cmsApi.getChaptersBySubCategory(formData.subCategoryId) : [],
    enabled: !!formData.subCategoryId,
  });

  const chapters = chaptersData || [];

  // Fetch MCQ categories
  const { data: mcqCategoriesData } = useQuery({
    queryKey: ['mcq-categories'],
    queryFn: () => cmsApi.getMcqCategories(),
  });

  const mcqCategories = Array.isArray(mcqCategoriesData) ? mcqCategoriesData : (mcqCategoriesData?.data || []);

  // Sub-category options removed - sub-categories are now simple text input

  // Fetch existing item if editing
  const { data: existingItem, isLoading: isLoadingItem } = useQuery({
    queryKey: ['general-knowledge-item', id],
    queryFn: async () => {
      const items = await cmsApi.getGeneralKnowledge({});
      return Array.isArray(items) ? items.find((item: any) => item.id === id) : null;
    },
    enabled: isEditMode && !!id,
  });

  // Update form when existing item loads
  useEffect(() => {
    if (existingItem && isEditMode) {
      const metadata = existingItem.metadata || {};
      setFormData({
        title: existingItem.title || '',
        description: existingItem.description || '',
        fullArticle: metadata.fullArticle || '',
        category: metadata.category || '',
        subCategory: metadata.subCategory || '',
        subCategoryId: metadata.subCategoryId || '',
        chapterId: metadata.chapterId || '',
        section: metadata.section || '',
        country: metadata.country || '',
        categoryId: existingItem.categoryId || '',
        imageUrl: existingItem.images?.[0] || '',
        imageFile: null,
        imagePreview: existingItem.images?.[0] || null,
        postType: metadata.postType || 'General Knowledge',
        targetedKeywords: metadata.targetedKeywords || '',
        autoGeneratedKeywords: metadata.autoGeneratedKeywords || '',
        language: metadata.language || 'ENGLISH',
        date: metadata.date || '',
        eventDates: metadata.eventDates || [],
        eventYearRange: metadata.eventYearRange || '',
        location: metadata.location || { lat: '', long: '' },
        state: metadata.state || '',
        district: metadata.district || '',
        city: metadata.city || '',
        isPublished: existingItem.isPublished || false,
        isActive: existingItem.isActive !== false,
        sendNotification: metadata.sendNotification || false,
        notificationTime: metadata.notificationTime || '',
        articleId: existingItem.id || '',
      });
    }
  }, [existingItem, isEditMode]);

  // Calculate word count for description (handles HTML content)
  // Uses DOMParser to safely extract text without executing scripts
  const getWordCount = (text: string) => {
    if (!text) return 0;
    try {
      // Use DOMParser to safely parse HTML without executing scripts
      const parser = new DOMParser();
      const doc = parser.parseFromString(text, 'text/html');
      const plainText = doc.body.textContent || doc.body.innerText || '';
      return plainText.trim().split(/\s+/).filter(word => word.length > 0).length;
    } catch (error) {
      // Fallback: strip HTML tags using regex if DOMParser fails
      const plainText = text.replace(/<[^>]*>/g, '').replace(/&[^;]+;/g, ' ');
      return plainText.trim().split(/\s+/).filter(word => word.length > 0).length;
    }
  };

  const descriptionWordCount = getWordCount(formData.description);
  const isDescriptionValid = descriptionWordCount > 0 && descriptionWordCount <= 60;

  // Category creation removed - use Wall Categories in dashboard instead

  // Handle image file selection
  const handleImageUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      if (!file.type.startsWith('image/')) {
        showToast('Please select an image file', 'error');
        return;
      }
      if (file.size > 5 * 1024 * 1024) {
        showToast('Image size should be less than 5MB', 'error');
        return;
      }
      const reader = new FileReader();
      reader.onloadend = () => {
        setFormData(prev => ({
          ...prev,
          imageFile: file,
          imagePreview: reader.result as string,
          imageUrl: '',
        }));
      };
      reader.readAsDataURL(file);
    }
  };

  const removeImage = () => {
    setFormData(prev => ({
      ...prev,
      imageFile: null,
      imagePreview: null,
      imageUrl: '',
    }));
  };

  const createMutation = useMutation({
    mutationFn: (data: typeof formData) => {
      const imageUrl = data.imagePreview || data.imageUrl;
      return cmsApi.createGeneralKnowledge({
        title: data.title,
        description: data.description,
        categoryId: data.categoryId || undefined,
        images: imageUrl ? [imageUrl] : [],
        isActive: data.isActive,
        isPublished: data.isPublished,
        metadata: {
          fullArticle: data.fullArticle,
          category: data.category,
          subCategory: data.subCategory,
          subCategoryId: data.subCategoryId,
          chapterId: data.chapterId || undefined,
          section: data.section,
          country: data.country,
          postType: data.postType,
          targetedKeywords: data.targetedKeywords,
          autoGeneratedKeywords: data.autoGeneratedKeywords,
          language: data.language || 'ENGLISH',
          date: data.date || undefined,
          eventDates: data.eventDates,
          eventYearRange: data.eventYearRange,
          location: data.location,
          state: data.state,
          district: data.district,
          city: data.city,
          sendNotification: data.sendNotification,
          notificationTime: data.notificationTime,
        },
      });
    },
    onSuccess: (response) => {
      queryClient.invalidateQueries({ queryKey: ['general-knowledge'] });
      const createdArticle = Array.isArray(response) ? response[0] : response;
      const articleId = createdArticle?.id;
      if (articleId) {
        setFormData(prev => ({ ...prev, articleId }));
      }
      showToast('General knowledge article created successfully', 'success');
      // Don't navigate away - allow creating MCQ or publishing
    },
    onError: () => showToast('Failed to create article', 'error'),
  });

  const updateMutation = useMutation({
    mutationFn: (data: typeof formData) => {
      const imageUrl = data.imagePreview || data.imageUrl;
      return cmsApi.updateGeneralKnowledge(id!, {
        title: data.title,
        description: data.description,
        categoryId: data.categoryId || undefined,
        images: imageUrl ? [imageUrl] : [],
        isActive: data.isActive,
        isPublished: data.isPublished,
        metadata: {
          fullArticle: data.fullArticle,
          category: data.category,
          subCategory: data.subCategory,
          subCategoryId: data.subCategoryId,
          chapterId: data.chapterId || undefined,
          section: data.section,
          country: data.country,
          postType: data.postType,
          targetedKeywords: data.targetedKeywords,
          autoGeneratedKeywords: data.autoGeneratedKeywords,
          language: data.language || 'ENGLISH',
          date: data.date || undefined,
          eventDates: data.eventDates,
          eventYearRange: data.eventYearRange,
          location: data.location,
          state: data.state,
          district: data.district,
          city: data.city,
          sendNotification: data.sendNotification,
          notificationTime: data.notificationTime,
        },
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['general-knowledge'] });
      queryClient.invalidateQueries({ queryKey: ['general-knowledge-item', id] });
      showToast('Article updated successfully', 'success');
      navigate('/cms/general-knowledge');
    },
    onError: () => showToast('Failed to update article', 'error'),
  });

  const handleSubmit = () => {
    if (!formData.title.trim()) {
      showToast('Please enter a title', 'error');
      return;
    }
    if (!formData.description.trim()) {
      showToast('Please enter a description', 'error');
      return;
    }
    if (!isDescriptionValid) {
      showToast('Description must be 60 words or less', 'error');
      return;
    }

    if (isEditMode) {
      updateMutation.mutate(formData);
    } else {
      createMutation.mutate(formData);
    }
  };

  const handleCategoryChange = (value: string) => {
    const selectedCategory = categories.find((cat: any) => cat.id === value);
    setFormData(prev => ({
      ...prev,
      categoryId: value,
      category: selectedCategory?.name || prev.category,
      subCategory: '',
      subCategoryId: '',
    }));
  };

  // MCQ Dialog handlers
  const handleOpenMcqDialog = () => {
    // Pre-fill MCQ category if available
    if (formData.categoryId) {
      const matchingCategory = mcqCategories.find((cat: any) => 
        cat.id === formData.categoryId || cat.name?.toLowerCase().includes(formData.category?.toLowerCase() || '')
      );
      if (matchingCategory) {
        setMcqFormData(prev => ({ ...prev, categoryId: matchingCategory.id }));
      }
    }
    setIsMcqDialogOpen(true);
  };

  const handleCloseMcqDialog = () => {
    setIsMcqDialogOpen(false);
    // Reset form and created MCQs list when closing
    setMcqFormData({
      question: '',
      options: ['', '', '', ''],
      correctAnswer: 0,
      categoryId: '',
      explanation: '',
    });
    setCreatedMcqs([]);
  };

  const updateMcqOption = (index: number, value: string) => {
    const newOptions = [...mcqFormData.options];
    newOptions[index] = value;
    setMcqFormData({ ...mcqFormData, options: newOptions });
  };

  const createMcqMutation = useMutation({
    mutationFn: (data: typeof mcqFormData) => {
      const articleId = formData.articleId || id;
      return cmsApi.createMcqQuestion({
        question: data.question,
        options: data.options.map((opt, idx) => ({
          text: opt,
          isCorrect: idx === data.correctAnswer,
        })),
        correctAnswer: data.correctAnswer,
        categoryId: data.categoryId || undefined,
        explanation: data.explanation || undefined,
        articleId: articleId || undefined,
        metadata: {
          articleId: articleId,
          category: formData.category || undefined,
          subCategory: formData.subCategory || undefined,
          section: formData.section || undefined,
          country: formData.country || undefined,
        },
      });
    },
    onSuccess: (response) => {
      queryClient.invalidateQueries({ queryKey: ['mcq-questions'] });
      const createdMcq = Array.isArray(response) ? response[0] : response;
      setCreatedMcqs(prev => [...prev, createdMcq]);
      showToast('MCQ question created successfully', 'success');
      // Reset form but keep dialog open
      setMcqFormData({
        question: '',
        options: ['', '', '', ''],
        correctAnswer: 0,
        categoryId: mcqFormData.categoryId, // Keep category
        explanation: '',
      });
    },
    onError: () => showToast('Failed to create MCQ question', 'error'),
  });

  const handleCreateMcq = () => {
    if (!mcqFormData.question.trim()) {
      showToast('Please enter a question', 'error');
      return;
    }
    if (mcqFormData.options.filter(opt => opt.trim()).length < 2) {
      showToast('Please provide at least 2 options', 'error');
      return;
    }
    if (mcqFormData.correctAnswer < 0 || mcqFormData.correctAnswer >= mcqFormData.options.length) {
      showToast('Please select a valid correct answer', 'error');
      return;
    }
    // Warn if article not created yet, but still allow creating MCQ
    if (!formData.articleId && !id) {
      showToast('Note: MCQ will be created without article link. Create article first to link them.', 'info');
    }
    createMcqMutation.mutate(mcqFormData);
  };

  if (isLoadingItem && isEditMode) {
    return (
      <AdminLayout>
        <div className="flex items-center justify-center h-96">
          <Loader2 className="h-8 w-8 animate-spin text-blue-600" />
        </div>
      </AdminLayout>
    );
  }

  return (
    <>
      <style>{`
        .article-preview-content p {
          margin: 0.5rem 0;
        }
        .article-preview-content p:first-child {
          margin-top: 0;
        }
        .article-preview-content p:last-child {
          margin-bottom: 0;
        }
        .article-preview-content strong,
        .article-preview-content b {
          font-weight: 600;
        }
        .article-preview-content em,
        .article-preview-content i {
          font-style: italic;
        }
        .article-preview-content u {
          text-decoration: underline;
        }
        .article-preview-content a {
          color: #3b82f6;
          text-decoration: underline;
        }
        .article-preview-content ul,
        .article-preview-content ol {
          margin: 0.5rem 0;
          padding-left: 1.5rem;
        }
        .article-preview-content h1,
        .article-preview-content h2,
        .article-preview-content h3,
        .article-preview-content h4,
        .article-preview-content h5,
        .article-preview-content h6 {
          font-weight: 600;
          margin: 0.75rem 0 0.5rem 0;
        }
        .article-preview-content h1 { font-size: 1.5rem; }
        .article-preview-content h2 { font-size: 1.25rem; }
        .article-preview-content h3 { font-size: 1.125rem; }
        .article-preview-content blockquote {
          border-left: 3px solid #cbd5e1;
          padding-left: 1rem;
          margin: 0.5rem 0;
          font-style: italic;
          color: #64748b;
        }
      `}</style>
      <AdminLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button
              variant="ghost"
              onClick={() => navigate('/cms/general-knowledge')}
              className="hover:bg-slate-100"
            >
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to General Knowledge
            </Button>
            <div>
              <h1 className="text-3xl font-bold text-slate-900">
                {isEditMode ? 'Edit General Knowledge Article' : 'Create General Knowledge Article'}
              </h1>
              <p className="text-slate-600 mt-1">
                {isEditMode ? 'Update article details' : 'Add a new general knowledge article'}
              </p>
            </div>
          </div>
          <Button
            onClick={handleSubmit}
            disabled={createMutation.isPending || updateMutation.isPending || !isDescriptionValid}
            className="bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white font-semibold shadow-lg"
          >
            {(createMutation.isPending || updateMutation.isPending) ? (
              <>
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                {isEditMode ? 'Updating...' : 'Creating...'}
              </>
            ) : (
              <>
                <Save className="h-4 w-4 mr-2" />
                {isEditMode ? 'Update Article' : 'Create Article'}
              </>
            )}
          </Button>
        </div>

        {/* Main Content - Side by Side */}
        <div className="grid gap-6 lg:grid-cols-2">
          {/* Left Side - Form */}
          <Card className="border-0 shadow-xl bg-white">
            <CardHeader className="border-b border-slate-200 bg-gradient-to-r from-blue-50/50 to-white">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-xl bg-gradient-to-br from-blue-500 to-blue-600 shadow-md">
                  <BookOpen className="h-5 w-5 text-white" />
                </div>
                <div>
                  <CardTitle className="text-lg font-bold text-slate-900">Article Details</CardTitle>
                  <CardDescription className="text-slate-600">Enter general knowledge information</CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent className="pt-6 space-y-8">
              {/* Section 1: Category and Basic Information */}
              <div className="space-y-4 pb-6 border-b border-slate-200">
                <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
                  <Tag className="h-5 w-5 text-blue-600" />
                  Category and Basic Information
                </h3>
                
                {/* Category Fields */}
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <label className="text-sm font-semibold text-slate-700">Category *</label>
                    <select
                      value={formData.categoryId}
                      onChange={(e) => handleCategoryChange(e.target.value)}
                      className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                    >
                      <option value="">Select Category</option>
                      {categories.map((cat: any) => (
                        <option key={cat.id} value={cat.id}>
                          {cat.name}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div className="space-y-2">
                    <label className="text-sm font-semibold text-slate-700">Sub Category</label>
                    <select
                      value={formData.subCategoryId}
                      onChange={(e) => {
                        const value = e.target.value;
                        const selected = subCategories.find((sub: any) => sub.id === value);
                        setFormData({
                          ...formData,
                          subCategoryId: value,
                          subCategory: selected?.name || '',
                        });
                      }}
                      className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                      disabled={!formData.categoryId || subCategories.length === 0}
                    >
                      <option value="">Select Sub Category</option>
                      {subCategories.map((sub: any) => (
                        <option key={sub.id} value={sub.id}>
                          {sub.name}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div className="space-y-2">
                    <label className="text-sm font-semibold text-slate-700">Chapter</label>
                    <select
                      value={formData.chapterId}
                      onChange={(e) =>
                        setFormData({ ...formData, chapterId: e.target.value })
                      }
                      className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                      disabled={!formData.subCategoryId || chapters.length === 0}
                    >
                      <option value="">Select Chapter</option>
                      {chapters.map((chapter: Chapter) => (
                        <option key={chapter.id} value={chapter.id}>
                          {chapter.name}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div>
                    <label className="text-sm font-semibold text-slate-700 mb-2 block">Section</label>
                    <Input
                      placeholder="Enter section"
                      value={formData.section}
                      onChange={(e) => setFormData({ ...formData, section: e.target.value })}
                      className="mt-1"
                    />
                  </div>
                </div>

                {/* Title */}
                <div>
                  <label className="text-sm font-semibold text-slate-700 mb-2 block">Title *</label>
                  <Input
                    placeholder="Enter article title"
                    value={formData.title}
                    onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                    className="mt-1"
                  />
                </div>

                {/* Language */}
                <div className="bg-blue-50 p-4 rounded-lg border border-blue-200">
                  <label className="text-sm font-semibold text-slate-700 mb-2 block">Language *</label>
                  <select
                    value={formData.language || 'ENGLISH'}
                    onChange={(e) => setFormData({ ...formData, language: e.target.value })}
                    className="w-full px-3 py-2 border-2 border-blue-300 rounded-md text-sm font-medium bg-white focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  >
                    <option value="ENGLISH">English</option>
                    <option value="HINDI">Hindi (हिंदी)</option>
                  </select>
                  <p className="text-xs text-slate-600 mt-2 font-medium">Select the language of the article content</p>
                </div>
              </div>

              {/* Section 2: Date and Location Details */}
              <div className="space-y-4 pb-6 border-b border-slate-200">
                <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
                  <Calendar className="h-5 w-5 text-blue-600" />
                  Date and Location Details
                </h3>

                {/* Event Date */}
                <div>
                  <label className="text-sm font-semibold text-slate-700 mb-2 block flex items-center gap-2">
                    Event Date
                  </label>
                  <Input
                    type="date"
                    value={formData.date}
                    onChange={(e) => setFormData({ ...formData, date: e.target.value })}
                    className="mt-1"
                  />
                </div>

                {/* Notification Date */}
                <div>
                  <label className="text-sm font-semibold text-slate-700 mb-2 block">
                    Notification Date (Month & Day)
                  </label>
                  <div className="space-y-2">
                    {formData.eventDates.map((date, index) => (
                      <div key={index} className="flex items-center gap-2">
                        <Input
                          type="text"
                          value={date}
                          onChange={(e) => {
                            const newDates = [...formData.eventDates];
                            newDates[index] = e.target.value;
                            setFormData({ ...formData, eventDates: newDates });
                          }}
                          className="flex-1"
                          placeholder="MM-DD"
                        />
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => {
                            const newDates = formData.eventDates.filter((_, i) => i !== index);
                            setFormData({ ...formData, eventDates: newDates });
                          }}
                        >
                          Remove
                        </Button>
                      </div>
                    ))}
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => {
                        setFormData({ ...formData, eventDates: [...formData.eventDates, ''] });
                      }}
                    >
                      Add More Dates
                    </Button>
                  </div>
                  <p className="text-xs text-slate-500 mt-1">
                    Notifications will be sent automatically on these dates each year (use MM-DD format).
                  </p>
                </div>

                {/* Event Year Range */}
                <div>
                  <label className="text-sm font-semibold text-slate-700 mb-2 block">Event Year Range</label>
                  <Input
                    placeholder="e.g., 2020-2024"
                    value={formData.eventYearRange}
                    onChange={(e) => setFormData({ ...formData, eventYearRange: e.target.value })}
                    className="mt-1"
                  />
                </div>

                {/* Location Section */}
                <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
                  <label className="text-sm font-semibold text-slate-700 mb-3 block flex items-center gap-2">
                    <MapPin className="h-4 w-4" />
                    Location
                  </label>
                  
                  {/* Longitude and Latitude */}
                  <div className="grid grid-cols-2 gap-3 mb-4">
                    <div>
                      <label className="text-xs text-slate-600 mb-1 block">Longitude</label>
                      <Input
                        type="number"
                        step="any"
                        placeholder="e.g., 77.2090"
                        value={formData.location.long}
                        onChange={(e) => setFormData({
                          ...formData,
                          location: { ...formData.location, long: e.target.value }
                        })}
                        className="mt-1"
                      />
                    </div>
                    <div>
                      <label className="text-xs text-slate-600 mb-1 block">Latitude</label>
                      <Input
                        type="number"
                        step="any"
                        placeholder="e.g., 28.6139"
                        value={formData.location.lat}
                        onChange={(e) => setFormData({
                          ...formData,
                          location: { ...formData.location, lat: e.target.value }
                        })}
                        className="mt-1"
                      />
                    </div>
                  </div>

                  {/* Country, State, District, City */}
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="text-xs text-slate-600 mb-1 block">Country *</label>
                      <Input
                        placeholder="Enter country"
                        value={formData.country}
                        onChange={(e) => setFormData({ ...formData, country: e.target.value })}
                        className="mt-1"
                      />
                    </div>
                    <div>
                      <label className="text-xs text-slate-600 mb-1 block">State</label>
                      <Input
                        placeholder="Enter state"
                        value={formData.state}
                        onChange={(e) => setFormData({ ...formData, state: e.target.value })}
                        className="mt-1"
                      />
                    </div>
                    <div>
                      <label className="text-xs text-slate-600 mb-1 block">District</label>
                      <Input
                        placeholder="Enter district"
                        value={formData.district}
                        onChange={(e) => setFormData({ ...formData, district: e.target.value })}
                        className="mt-1"
                      />
                    </div>
                    <div>
                      <label className="text-xs text-slate-600 mb-1 block">City</label>
                      <Input
                        placeholder="Enter city"
                        value={formData.city}
                        onChange={(e) => setFormData({ ...formData, city: e.target.value })}
                        className="mt-1"
                      />
                    </div>
                  </div>
                </div>
              </div>

              {/* Section 3: Content */}
              <div className="space-y-4">
                <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
                  <BookOpen className="h-5 w-5 text-blue-600" />
                  Content
                </h3>

                {/* Image Upload */}
                <div>
                  <label className="text-sm font-semibold text-slate-700 mb-2 block flex items-center gap-2">
                    <ImageIcon className="h-4 w-4" />
                    Image Upload
                  </label>
                <RichTextEditor
                  value={formData.description}
                  onChange={(value) => {
                    // Limit to 60 words
                    const wordCount = getWordCount(value);
                    if (wordCount > 60) {
                      // Truncate to 60 words
                      const parser = new DOMParser();
                      const doc = parser.parseFromString(value, 'text/html');
                      const plainText = doc.body.textContent || doc.body.innerText || '';
                      const words = plainText.trim().split(/\s+/).filter(word => word.length > 0);
                      
                      if (words.length > 60) {
                        const truncatedWords = words.slice(0, 60);
                        const truncatedText = truncatedWords.join(' ');
                        
                        // If original had HTML, try to preserve structure by replacing text content
                        // Otherwise, just use the truncated plain text
                        let truncatedValue = value;
                        if (value.includes('<')) {
                          // Find the text content in the HTML and replace it
                          const body = doc.body;
                          if (body) {
                            body.textContent = truncatedText;
                            truncatedValue = body.innerHTML || truncatedText;
                          } else {
                            truncatedValue = truncatedText;
                          }
                        } else {
                          truncatedValue = truncatedText;
                        }
                        
                        setFormData({ ...formData, description: truncatedValue });
                        showToast('Description limited to 60 words', 'info');
                      } else {
                        setFormData({ ...formData, description: value });
                      }
                    } else {
                      setFormData({ ...formData, description: value });
                    }
                  }}
                  placeholder="Write a brief description (max 60 words) with full formatting options..."
                  minHeight="200px"
                  className="mt-1"
                />
                <div className="mt-2 flex items-center justify-between">
                  <p className={`text-xs ${isDescriptionValid ? 'text-emerald-600' : descriptionWordCount > 60 ? 'text-red-600' : 'text-slate-600'}`}>
                    {descriptionWordCount} / 60 words {descriptionWordCount > 60 && `(Exceeds limit)`}
                  </p>
                  {isDescriptionValid && (
                    <span className="text-xs text-emerald-600 font-semibold">✓ Valid</span>
                  )}
                </div>
              </div>

                {/* Image Upload */}
                <div>
                  <label className="text-sm font-semibold text-slate-700 mb-2 block flex items-center gap-2">
                    <ImageIcon className="h-4 w-4" />
                    Image Upload
                  </label>
                
                {formData.imagePreview || formData.imageUrl ? (
                  <div className="mt-2 space-y-3">
                    <div className="relative">
                      <img
                        src={formData.imagePreview || formData.imageUrl}
                        alt="Article preview"
                        className="w-full max-w-md h-48 object-cover rounded-lg border-2 border-slate-200 bg-slate-50"
                        onError={(e) => {
                          (e.target as HTMLImageElement).style.display = 'none';
                        }}
                      />
                      <button
                        type="button"
                        onClick={removeImage}
                        className="absolute top-2 right-2 p-2 bg-red-500 text-white rounded-full hover:bg-red-600 transition-colors shadow-lg"
                      >
                        <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                      </button>
                    </div>
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() => document.getElementById('image-upload')?.click()}
                      className="flex-1"
                    >
                      <ImageIcon className="h-4 w-4 mr-2" />
                      Change Image
                    </Button>
                  </div>
                ) : (
                  <div className="mt-2">
                    <input
                      type="file"
                      id="image-upload"
                      accept="image/*"
                      onChange={handleImageUpload}
                      className="hidden"
                    />
                    <label htmlFor="image-upload">
                      <div className="border-2 border-dashed border-slate-300 rounded-xl p-6 text-center hover:border-blue-400 transition-colors cursor-pointer bg-slate-50 hover:bg-blue-50/50">
                        <div className="flex flex-col items-center gap-3">
                          <div className="p-3 rounded-full bg-blue-100">
                            <ImageIcon className="h-6 w-6 text-blue-600" />
                          </div>
                          <div>
                            <p className="text-sm font-semibold text-slate-900 mb-1">Click to upload image</p>
                            <p className="text-xs text-slate-500">PNG, JPG, GIF up to 5MB</p>
                          </div>
                        </div>
                      </div>
                    </label>
                  </div>
                )}

                {/* Alternative: Image URL */}
                <div className="mt-4 pt-4 border-t border-slate-200">
                  <details className="group">
                    <summary className="text-xs font-medium text-slate-600 cursor-pointer hover:text-slate-900">
                      Or use image URL instead
                    </summary>
                    <div className="mt-2">
                      <Input
                        placeholder="https://example.com/image.jpg"
                        value={formData.imageUrl}
                        onChange={(e) => {
                          if (e.target.value) {
                            setFormData({ 
                              ...formData, 
                              imageUrl: e.target.value,
                              imageFile: null,
                              imagePreview: null,
                            });
                          }
                        }}
                        className="mt-1"
                        disabled={!!formData.imagePreview}
                      />
                    </div>
                  </details>
                </div>
                </div>

                {/* Description */}
                <div>
                  <label className="text-sm font-semibold text-slate-700 mb-2 block">
                    Description * (Max 60 words)
                  </label>
                  <RichTextEditor
                    value={formData.description}
                    onChange={(value) => {
                      // Limit to 60 words
                      const wordCount = getWordCount(value);
                      if (wordCount > 60) {
                        // Truncate to 60 words
                        const parser = new DOMParser();
                        const doc = parser.parseFromString(value, 'text/html');
                        const plainText = doc.body.textContent || doc.body.innerText || '';
                        const words = plainText.trim().split(/\s+/).filter(word => word.length > 0);
                        
                        if (words.length > 60) {
                          const truncatedWords = words.slice(0, 60);
                          const truncatedText = truncatedWords.join(' ');
                          
                          // If original had HTML, try to preserve structure by replacing text content
                          // Otherwise, just use the truncated plain text
                          let truncatedValue = value;
                          if (value.includes('<')) {
                            // Find the text content in the HTML and replace it
                            const body = doc.body;
                            if (body) {
                              body.textContent = truncatedText;
                              truncatedValue = body.innerHTML || truncatedText;
                            } else {
                              truncatedValue = truncatedText;
                            }
                          } else {
                            truncatedValue = truncatedText;
                          }
                          
                          setFormData({ ...formData, description: truncatedValue });
                          showToast('Description limited to 60 words', 'info');
                        } else {
                          setFormData({ ...formData, description: value });
                        }
                      } else {
                        setFormData({ ...formData, description: value });
                      }
                    }}
                    placeholder="Write a brief description (max 60 words) with full formatting options..."
                    minHeight="200px"
                    className="mt-1"
                  />
                  <div className="mt-2 flex items-center justify-between">
                    <p className={`text-xs ${isDescriptionValid ? 'text-emerald-600' : descriptionWordCount > 60 ? 'text-red-600' : 'text-slate-600'}`}>
                      {descriptionWordCount} / 60 words {descriptionWordCount > 60 && `(Exceeds limit)`}
                    </p>
                    {isDescriptionValid && (
                      <span className="text-xs text-emerald-600 font-semibold">✓ Valid</span>
                    )}
                  </div>
                </div>

                {/* Full Article */}
                <div>
                  <label className="text-sm font-semibold text-slate-700 mb-2 block">Full Article</label>
                  <RichTextEditor
                    value={formData.fullArticle}
                    onChange={(value) => setFormData({ ...formData, fullArticle: value })}
                    placeholder="Write the complete article content with full formatting options..."
                    minHeight="400px"
                    className="mt-1"
                  />
                  <p className="text-xs text-slate-500 mt-2">
                    This is the complete article content. Use the toolbar above to format your text (bold, italic, underline, alignment, links, etc.). The description above is a brief summary (max 60 words).
                  </p>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="space-y-4 pt-4 border-t border-slate-200 mt-6">
                <div className="flex items-center gap-2">
                  <Button
                    type="button"
                    onClick={handleSubmit}
                    disabled={createMutation.isPending || updateMutation.isPending || !isDescriptionValid}
                    className="flex-1 bg-gradient-to-r from-blue-600 to-indigo-600"
                  >
                    {(createMutation.isPending || updateMutation.isPending) ? (
                      <>
                        <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                        {isEditMode ? 'Updating...' : 'Creating...'}
                      </>
                    ) : (
                      <>
                        <Save className="h-4 w-4 mr-2" />
                        {isEditMode ? 'Update Article' : 'Create Article Page'}
                      </>
                    )}
                  </Button>
                  <Button
                    type="button"
                    variant="outline"
                    onClick={handleOpenMcqDialog}
                    className="flex-1"
                  >
                    <HelpCircle className="h-4 w-4 mr-2" />
                    Create MCQ
                  </Button>
                  <Button
                    type="button"
                    variant="destructive"
                    onClick={() => {
                      if (window.confirm('Are you sure you want to reject this article?')) {
                        setFormData(prev => ({ ...prev, isActive: false }));
                        showToast('Article rejected', 'info');
                      }
                    }}
                    className="flex-1"
                  >
                    Reject
                  </Button>
                </div>

                {/* Publish/Deactivate/Send Notification */}
                <div className="grid grid-cols-2 gap-4">
                  <div className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      id="publish"
                      checked={formData.isPublished}
                      onChange={(e) => setFormData({ ...formData, isPublished: e.target.checked })}
                      className="h-4 w-4 text-blue-600 rounded"
                    />
                    <label htmlFor="publish" className="text-sm font-medium text-slate-700 cursor-pointer">
                      Publish
                    </label>
                  </div>
                  <div className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      id="deactivate"
                      checked={!formData.isActive}
                      onChange={(e) => setFormData({ ...formData, isActive: !e.target.checked })}
                      className="h-4 w-4 text-blue-600 rounded"
                    />
                    <label htmlFor="deactivate" className="text-sm font-medium text-slate-700 cursor-pointer">
                      Deactivate
                    </label>
                  </div>
                </div>

                <div className="space-y-2">
                  <div className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      id="sendNotification"
                      checked={formData.sendNotification}
                      onChange={(e) => setFormData({ ...formData, sendNotification: e.target.checked })}
                      className="h-4 w-4 text-blue-600 rounded"
                    />
                    <label htmlFor="sendNotification" className="text-sm font-medium text-slate-700 cursor-pointer">
                      Send Notification
                    </label>
                  </div>
                  {formData.sendNotification && (
                    <div>
                      <label className="text-xs text-slate-600 mb-1 block">Select clock time else current time</label>
                      <Input
                        type="time"
                        value={formData.notificationTime}
                        onChange={(e) => setFormData({ ...formData, notificationTime: e.target.value })}
                        className="w-full"
                      />
                    </div>
                  )}
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Right Side - Live Preview */}
          <Card className="border-0 shadow-xl bg-white sticky top-6">
            <CardHeader className="border-b border-slate-200 bg-gradient-to-r from-emerald-50/50 to-white">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-xl bg-gradient-to-br from-emerald-500 to-emerald-600 shadow-md">
                  <Eye className="h-5 w-5 text-white" />
                </div>
                <div>
                  <CardTitle className="text-lg font-bold text-slate-900">Live Preview</CardTitle>
                  <CardDescription className="text-slate-600">See how your article will appear</CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent className="pt-6">
              <div className="space-y-4">
                {/* Preview Container */}
                <div className="bg-gradient-to-br from-slate-50 to-slate-100 rounded-xl p-6 border-2 border-dashed border-slate-300">
                  <div className="text-center mb-4">
                    <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">
                      Article Preview
                    </p>
                    <div className="w-full h-px bg-slate-200 mb-4"></div>
                  </div>

                  {/* Article Preview Card */}
                  <div className="bg-white rounded-xl shadow-lg overflow-hidden border border-slate-200">
                    {(formData.imagePreview || formData.imageUrl) && (
                      <div className="w-full h-48 bg-slate-100 overflow-hidden">
                        <img
                          src={formData.imagePreview || formData.imageUrl}
                          alt="Article"
                          className="w-full h-full object-cover"
                          onError={(e) => {
                            (e.target as HTMLImageElement).style.display = 'none';
                          }}
                        />
                      </div>
                    )}
                    <div className="p-4 space-y-3">
                      {formData.title ? (
                        <h3 className="text-xl font-bold text-slate-900">{formData.title}</h3>
                      ) : (
                        <div className="h-6 bg-slate-200 rounded animate-pulse"></div>
                      )}
                      {formData.description ? (
                        <div 
                          className="text-sm text-slate-600 line-clamp-4 article-preview-content"
                          style={{ 
                            overflow: 'hidden',
                            display: '-webkit-box',
                            WebkitLineClamp: 4,
                            WebkitBoxOrient: 'vertical'
                          }}
                          dangerouslySetInnerHTML={{ __html: formData.description }}
                        />
                      ) : (
                        <div className="space-y-2">
                          <div className="h-4 bg-slate-200 rounded animate-pulse"></div>
                          <div className="h-4 bg-slate-200 rounded animate-pulse w-5/6"></div>
                          <div className="h-4 bg-slate-200 rounded animate-pulse w-4/6"></div>
                        </div>
                      )}
                      <div className="pt-2 border-t border-slate-200">
                        <div className="flex items-center gap-2 text-xs text-slate-500">
                          <BookOpen className="h-3 w-3" />
                          <span>General Knowledge</span>
                          <span>•</span>
                          <span>{new Date().toLocaleDateString()}</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Preview Info */}
                  <div className="mt-4 p-3 rounded-lg bg-blue-50 border border-blue-200">
                    <p className="text-xs text-blue-800">
                      <strong>Preview Note:</strong> This is how the general knowledge article will appear to users on the platform.
                    </p>
                  </div>
                </div>

                {/* Preview Status */}
                <div className="space-y-2">
                  <div className="flex items-center justify-between p-3 rounded-lg bg-slate-50 border border-slate-200">
                    <span className="text-sm font-medium text-slate-700">Title Status</span>
                    <span className={`text-xs font-semibold px-2 py-1 rounded-full ${
                      formData.title
                        ? 'bg-emerald-100 text-emerald-700 border border-emerald-200'
                        : 'bg-yellow-100 text-yellow-700 border border-yellow-200'
                    }`}>
                      {formData.title ? '✓ Title Set' : '⚠ Required'}
                    </span>
                  </div>
                  <div className="flex items-center justify-between p-3 rounded-lg bg-slate-50 border border-slate-200">
                    <span className="text-sm font-medium text-slate-700">Content Status</span>
                    <span className={`text-xs font-semibold px-2 py-1 rounded-full ${
                      formData.description
                        ? 'bg-emerald-100 text-emerald-700 border border-emerald-200'
                        : 'bg-yellow-100 text-yellow-700 border border-yellow-200'
                    }`}>
                      {formData.description ? '✓ Content Set' : '⚠ Required'}
                    </span>
                  </div>
                  <div className="flex items-center justify-between p-3 rounded-lg bg-slate-50 border border-slate-200">
                    <span className="text-sm font-medium text-slate-700">Image Status</span>
                    <span className={`text-xs font-semibold px-2 py-1 rounded-full ${
                      formData.imagePreview || formData.imageUrl
                        ? 'bg-emerald-100 text-emerald-700 border border-emerald-200'
                        : 'bg-slate-100 text-slate-600 border border-slate-200'
                    }`}>
                      {formData.imagePreview || formData.imageUrl ? '✓ Image Added' : '○ Optional'}
                    </span>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>

      {/* Category creation removed - use Wall Categories in dashboard instead */}

      {/* Create MCQ Dialog */}
      <Dialog open={isMcqDialogOpen} onOpenChange={setIsMcqDialogOpen}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center justify-between">
              <span>Create MCQ Questions</span>
              <Button
                variant="ghost"
                size="sm"
                onClick={handleCloseMcqDialog}
                className="h-6 w-6 p-0"
              >
                <X className="h-4 w-4" />
              </Button>
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-6">
            {/* Warning if article not created */}
            {!formData.articleId && !id && (
              <div className="p-3 rounded-lg bg-yellow-50 border border-yellow-200">
                <p className="text-sm text-yellow-800">
                  <strong>Note:</strong> The article hasn't been created yet. MCQs will be created without an article link. Create the article first to automatically link them.
                </p>
              </div>
            )}
            {/* Created MCQs List */}
            {createdMcqs.length > 0 && (
              <div className="border border-slate-200 rounded-lg p-4 bg-slate-50">
                <h3 className="text-sm font-semibold text-slate-700 mb-3">
                  Created MCQs ({createdMcqs.length})
                </h3>
                <div className="space-y-2 max-h-40 overflow-y-auto">
                  {createdMcqs.map((mcq, idx) => (
                    <div key={mcq.id || idx} className="flex items-center justify-between p-2 bg-white rounded border border-slate-200">
                      <div className="flex-1">
                        <p className="text-sm font-medium text-slate-900 line-clamp-1">
                          {mcq.question || `MCQ ${idx + 1}`}
                        </p>
                      </div>
                      <CheckCircle2 className="h-4 w-4 text-emerald-600 ml-2" />
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* MCQ Form */}
            <div className="space-y-4">
              {/* Category */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">Category</label>
                <select
                  value={mcqFormData.categoryId}
                  onChange={(e) => setMcqFormData({ ...mcqFormData, categoryId: e.target.value })}
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                >
                  <option value="">Select a category</option>
                  {mcqCategories.map((cat: any) => (
                    <option key={cat.id} value={cat.id}>
                      {cat.name}
                    </option>
                  ))}
                </select>
              </div>

              {/* Question */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">Question *</label>
                <Textarea
                  placeholder="Enter the question..."
                  value={mcqFormData.question}
                  onChange={(e) => setMcqFormData({ ...mcqFormData, question: e.target.value })}
                  className="min-h-[100px]"
                  rows={4}
                />
              </div>

              {/* Options */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">Answer Options *</label>
                <div className="space-y-3">
                  {mcqFormData.options.map((option, index) => (
                    <div key={index} className="flex items-center gap-3">
                      <div className={`flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center font-bold text-sm ${
                        mcqFormData.correctAnswer === index
                          ? 'bg-emerald-500 text-white'
                          : 'bg-slate-200 text-slate-600'
                      }`}>
                        {String.fromCharCode(65 + index)}
                      </div>
                      <Input
                        placeholder={`Option ${String.fromCharCode(65 + index)}`}
                        value={option}
                        onChange={(e) => updateMcqOption(index, e.target.value)}
                        className="flex-1"
                      />
                      <Button
                        type="button"
                        variant={mcqFormData.correctAnswer === index ? 'default' : 'outline'}
                        size="sm"
                        onClick={() => setMcqFormData({ ...mcqFormData, correctAnswer: index })}
                        className={mcqFormData.correctAnswer === index ? 'bg-emerald-600 hover:bg-emerald-700' : ''}
                      >
                        {mcqFormData.correctAnswer === index ? (
                          <CheckCircle2 className="h-4 w-4" />
                        ) : (
                          <XCircle className="h-4 w-4" />
                        )}
                      </Button>
                    </div>
                  ))}
                </div>
                <p className="text-xs text-slate-500 mt-2">Click the checkmark to mark the correct answer</p>
              </div>

              {/* Explanation */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">Explanation (Optional)</label>
                <Textarea
                  placeholder="Explain why this is the correct answer..."
                  value={mcqFormData.explanation}
                  onChange={(e) => setMcqFormData({ ...mcqFormData, explanation: e.target.value })}
                  className="min-h-[80px]"
                  rows={4}
                />
              </div>
            </div>
          </div>
          <DialogFooter className="flex items-center justify-between">
            <div className="text-sm text-slate-600">
              {createdMcqs.length > 0 && (
                <span className="text-emerald-600 font-medium">
                  {createdMcqs.length} MCQ{createdMcqs.length !== 1 ? 's' : ''} created
                </span>
              )}
            </div>
            <div className="flex gap-2">
              <Button
                variant="outline"
                onClick={handleCloseMcqDialog}
              >
                Done
              </Button>
              <Button
                onClick={handleCreateMcq}
                disabled={createMcqMutation.isPending}
                className="bg-gradient-to-r from-blue-600 to-indigo-600"
              >
                {createMcqMutation.isPending ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Creating...
                  </>
                ) : (
                  <>
                    <Plus className="h-4 w-4 mr-2" />
                    Add MCQ
                  </>
                )}
              </Button>
            </div>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </AdminLayout>
    </>
  );
}




















