import { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { AdminLayout } from '../../components/layout/AdminLayout';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../components/ui/card';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { Textarea } from '../../components/ui/textarea';
import { RichTextEditor } from '../../components/ui/RichTextEditor';
import { ArrowLeft, Save, Eye, Newspaper, Loader2, Image as ImageIcon, HelpCircle, CheckCircle2, XCircle, Plus, X, Calendar, MapPin } from 'lucide-react';
import { useToast } from '../../contexts/ToastContext';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { cmsApi } from '../../services/api/cms';
import { postsApi } from '../../services/api/posts';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '../../components/ui/dialog';

export default function CreateCurrentAffairPage() {
  const navigate = useNavigate();
  const { id } = useParams<{ id?: string }>();
  const isEditMode = !!id;
  const { showToast } = useToast();
  const queryClient = useQueryClient();

  const [isCategoryDialogOpen, setIsCategoryDialogOpen] = useState(false);
  const [newCategoryName, setNewCategoryName] = useState('');
  const [newCategoryDescription, setNewCategoryDescription] = useState('');
  const [newSubCategory, setNewSubCategory] = useState('');
  const [subCategoryOptions, setSubCategoryOptions] = useState<string[]>([]);
  
  // MCQ Dialog state
  const [isMcqDialogOpen, setIsMcqDialogOpen] = useState(false);
  const [mcqFormData, setMcqFormData] = useState({
    question: '',
    options: ['', '', '', ''],
    correctAnswer: 0,
    categoryId: '',
    explanation: '',
  });
  const [createdMcqs, setCreatedMcqs] = useState<any[]>([]);

  const [formData, setFormData] = useState({
    title: '',
    description: '',
    fullArticle: '',
    categoryId: '',
    subCategoryId: '',
    section: '',
    country: '',
    imageUrl: '',
    imageFile: null as File | null,
    imagePreview: null as string | null,
    // New fields
    postType: 'Current Affairs',
    headline: '',
    quickViewContent: '', // Under 60 words
    targetedKeywords: '',
    autoGeneratedKeywords: '',
    date: '', // Main article date
    eventDates: [] as string[], // Array of dates for notifications
    eventYearRange: '',
    location: {
      lat: '',
      long: '',
    },
    state: '',
    district: '',
    city: '',
    isPublished: false,
    isActive: true,
    sendNotification: false,
    notificationTime: '', // Clock time for notification
    articleId: '', // For linking MCQ
  });

  // Fetch categories
  const { data: categoriesData } = useQuery({
    queryKey: ['wall-categories'],
    queryFn: () => postsApi.getWallCategories(),
  });

  const categories = Array.isArray(categoriesData) ? categoriesData : (categoriesData?.data || []);

  // Fetch MCQ categories
  const { data: mcqCategoriesData } = useQuery({
    queryKey: ['mcq-categories'],
    queryFn: () => cmsApi.getMcqCategories(),
  });

  const mcqCategories = Array.isArray(mcqCategoriesData) ? mcqCategoriesData : (mcqCategoriesData?.data || []);

  useEffect(() => {
    const subs = new Set<string>();
    categories?.forEach((cat: any) => {
      if (Array.isArray(cat?.subCategories)) {
        cat.subCategories.forEach((sub: any) => {
          const label =
            typeof sub === 'string'
              ? sub
              : sub?.name || sub?.label || sub?.value || sub?.title;
          if (label) subs.add(label);
        });
      }
      const metaSub = cat?.metadata?.subCategory;
      if (typeof metaSub === 'string' && metaSub.trim()) {
        subs.add(metaSub.trim());
      }
    });
    setSubCategoryOptions(Array.from(subs));
  }, [categories]);

  // Calculate word count for description (handles HTML content)
  // Uses DOMParser to safely extract text without executing scripts
  const getWordCount = (text: string) => {
    if (!text) return 0;
    try {
      // Use DOMParser to safely parse HTML without executing scripts
      const parser = new DOMParser();
      const doc = parser.parseFromString(text, 'text/html');
      const plainText = doc.body.textContent || doc.body.innerText || '';
      return plainText.trim().split(/\s+/).filter(word => word.length > 0).length;
    } catch (error) {
      // Fallback: strip HTML tags using regex if DOMParser fails
      const plainText = text.replace(/<[^>]*>/g, '').replace(/&[^;]+;/g, ' ');
      return plainText.trim().split(/\s+/).filter(word => word.length > 0).length;
    }
  };

  const descriptionWordCount = getWordCount(formData.description);
  const isDescriptionValid = descriptionWordCount > 0 && descriptionWordCount <= 60;

  const createCategoryMutation = useMutation({
    mutationFn: (data: { name: string; description?: string }) => postsApi.createWallCategory(data),
    onSuccess: (createdCategory) => {
      queryClient.invalidateQueries({ queryKey: ['wall-categories'] });
      const created = Array.isArray(createdCategory) ? createdCategory[0] : createdCategory;
      const createdId = created?.id;
      const createdName = created?.name || newCategoryName;
      setFormData(prev => ({
        ...prev,
        categoryId: createdId || prev.categoryId,
        // keep sub-category choice intact
      }));
      if (createdName) {
        showToast(`Category "${createdName}" created`, 'success');
      } else {
        showToast('Category created successfully', 'success');
      }
      setIsCategoryDialogOpen(false);
      setNewCategoryName('');
      setNewCategoryDescription('');
    },
    onError: () => showToast('Failed to create category', 'error'),
  });

  // Fetch existing item if editing
  const { data: existingItem, isLoading: isLoadingItem } = useQuery({
    queryKey: ['current-affair', id],
    queryFn: async () => {
      const items = await cmsApi.getCurrentAffairs({});
      return Array.isArray(items) ? items.find((item: any) => item.id === id) : null;
    },
    enabled: isEditMode && !!id,
  });

  // Update form when existing item loads
  useEffect(() => {
    if (existingItem && isEditMode) {
      const metadata = existingItem.metadata || {};
      setFormData({
        title: existingItem.title || '',
        description: existingItem.description || '',
        fullArticle: metadata.fullArticle || '',
        categoryId: existingItem.categoryId || '',
        subCategoryId: metadata.subCategoryId || '',
        section: metadata.section || '',
        country: metadata.country || '',
        imageUrl: existingItem.images?.[0] || '',
        imageFile: null,
        imagePreview: existingItem.images?.[0] || null,
        postType: metadata.postType || 'Current Affairs',
        headline: metadata.headline || '',
        quickViewContent: metadata.quickViewContent || '',
        targetedKeywords: metadata.targetedKeywords || '',
        autoGeneratedKeywords: metadata.autoGeneratedKeywords || '',
        date: metadata.date || '',
        eventDates: metadata.eventDates || [],
        eventYearRange: metadata.eventYearRange || '',
        location: metadata.location || { lat: '', long: '' },
        state: metadata.state || '',
        district: metadata.district || '',
        city: metadata.city || '',
        isPublished: existingItem.isPublished || false,
        isActive: existingItem.isActive !== false,
        sendNotification: metadata.sendNotification || false,
        notificationTime: metadata.notificationTime || '',
        articleId: existingItem.id || '',
      });
    }
  }, [existingItem, isEditMode]);

  // Handle image file selection
  const handleImageUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      if (!file.type.startsWith('image/')) {
        showToast('Please select an image file', 'error');
        return;
      }
      if (file.size > 5 * 1024 * 1024) {
        showToast('Image size should be less than 5MB', 'error');
        return;
      }
      const reader = new FileReader();
      reader.onloadend = () => {
        setFormData(prev => ({
          ...prev,
          imageFile: file,
          imagePreview: reader.result as string,
          imageUrl: '',
        }));
      };
      reader.readAsDataURL(file);
    }
  };

  const removeImage = () => {
    setFormData(prev => ({
      ...prev,
      imageFile: null,
      imagePreview: null,
      imageUrl: '',
    }));
  };

  const createMutation = useMutation({
    mutationFn: (data: typeof formData) => {
      const imageUrl = data.imagePreview || data.imageUrl;
      return cmsApi.createCurrentAffair({
        title: data.title,
        description: data.description,
        categoryId: data.categoryId || undefined,
        images: imageUrl ? [imageUrl] : [],
        metadata: {
          fullArticle: data.fullArticle,
          subCategoryId: data.subCategoryId,
          section: data.section,
          country: data.country,
          date: data.date || undefined,
          location: data.location || undefined,
        },
      });
    },
    onSuccess: (response) => {
      queryClient.invalidateQueries({ queryKey: ['current-affairs'] });
      const createdArticle = Array.isArray(response) ? response[0] : response;
      const articleId = createdArticle?.id;
      if (articleId) {
        setFormData(prev => ({ ...prev, articleId }));
      }
      showToast('Current affair created successfully', 'success');
      // Don't navigate away - allow creating MCQ
    },
    onError: () => showToast('Failed to create current affair', 'error'),
  });

  const updateMutation = useMutation({
    mutationFn: (data: typeof formData) => {
      const imageUrl = data.imagePreview || data.imageUrl;
      return cmsApi.updateCurrentAffair(id!, {
        title: data.title,
        description: data.description,
        categoryId: data.categoryId || undefined,
        images: imageUrl ? [imageUrl] : [],
        metadata: {
          fullArticle: data.fullArticle,
          subCategoryId: data.subCategoryId,
          section: data.section,
          country: data.country,
          postType: data.postType,
          headline: data.headline,
          quickViewContent: data.quickViewContent,
          targetedKeywords: data.targetedKeywords,
          autoGeneratedKeywords: data.autoGeneratedKeywords,
          date: data.date || undefined,
          eventDates: data.eventDates,
          eventYearRange: data.eventYearRange,
          location: data.location,
          state: data.state,
          district: data.district,
          city: data.city,
          sendNotification: data.sendNotification,
          notificationTime: data.notificationTime,
        },
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['current-affairs'] });
      queryClient.invalidateQueries({ queryKey: ['current-affair', id] });
      showToast('Current affair updated successfully', 'success');
      navigate('/cms/current-affairs');
    },
    onError: () => showToast('Failed to update current affair', 'error'),
  });

  const handleSubmit = () => {
    if (!formData.title.trim()) {
      showToast('Please enter a title', 'error');
      return;
    }
    if (!formData.description.trim()) {
      showToast('Please enter a description', 'error');
      return;
    }
    if (!isDescriptionValid) {
      showToast('Description must be 60 words or less', 'error');
      return;
    }

    if (isEditMode) {
      updateMutation.mutate(formData);
    } else {
      createMutation.mutate(formData);
    }
  };

  const handleCategoryChange = (value: string) => {
    if (value === '__create__') {
      setIsCategoryDialogOpen(true);
      return;
    }
    setFormData(prev => ({ ...prev, categoryId: value }));
  };

  const handleAddSubCategory = () => {
    const trimmed = newSubCategory.trim();
    if (!trimmed) return;
    setSubCategoryOptions(prev => (prev.includes(trimmed) ? prev : [...prev, trimmed]));
    setFormData(prev => ({ ...prev, subCategoryId: trimmed }));
    setNewSubCategory('');
    showToast('Sub-category added', 'success');
  };

  // MCQ Dialog handlers
  const handleOpenMcqDialog = () => {
    // Pre-fill MCQ category if available
    if (formData.categoryId) {
      const matchingCategory = mcqCategories.find((cat: any) => 
        cat.id === formData.categoryId
      );
      if (matchingCategory) {
        setMcqFormData(prev => ({ ...prev, categoryId: matchingCategory.id }));
      }
    }
    setIsMcqDialogOpen(true);
  };

  const handleCloseMcqDialog = () => {
    setIsMcqDialogOpen(false);
    // Reset form and created MCQs list when closing
    setMcqFormData({
      question: '',
      options: ['', '', '', ''],
      correctAnswer: 0,
      categoryId: '',
      explanation: '',
    });
    setCreatedMcqs([]);
  };

  const updateMcqOption = (index: number, value: string) => {
    const newOptions = [...mcqFormData.options];
    newOptions[index] = value;
    setMcqFormData({ ...mcqFormData, options: newOptions });
  };

  const createMcqMutation = useMutation({
    mutationFn: (data: typeof mcqFormData) => {
      const articleId = formData.articleId || id;
      // Find category name from categories
      const categoryName = categories.find((cat: any) => cat.id === formData.categoryId)?.name;
      return cmsApi.createMcqQuestion({
        question: data.question,
        options: data.options.map((opt, idx) => ({
          text: opt,
          isCorrect: idx === data.correctAnswer,
        })),
        correctAnswer: data.correctAnswer,
        categoryId: data.categoryId || undefined,
        explanation: data.explanation || undefined,
        articleId: articleId || undefined,
        metadata: {
          articleId: articleId,
          category: categoryName || undefined,
          subCategory: formData.subCategoryId || undefined,
          section: formData.section || undefined,
          country: formData.country || undefined,
        },
      });
    },
    onSuccess: (response) => {
      queryClient.invalidateQueries({ queryKey: ['mcq-questions'] });
      const createdMcq = Array.isArray(response) ? response[0] : response;
      setCreatedMcqs(prev => [...prev, createdMcq]);
      showToast('MCQ question created successfully', 'success');
      // Reset form but keep dialog open
      setMcqFormData({
        question: '',
        options: ['', '', '', ''],
        correctAnswer: 0,
        categoryId: mcqFormData.categoryId, // Keep category
        explanation: '',
      });
    },
    onError: () => showToast('Failed to create MCQ question', 'error'),
  });

  const handleCreateMcq = () => {
    if (!mcqFormData.question.trim()) {
      showToast('Please enter a question', 'error');
      return;
    }
    if (mcqFormData.options.filter(opt => opt.trim()).length < 2) {
      showToast('Please provide at least 2 options', 'error');
      return;
    }
    if (mcqFormData.correctAnswer < 0 || mcqFormData.correctAnswer >= mcqFormData.options.length) {
      showToast('Please select a valid correct answer', 'error');
      return;
    }
    // Warn if article not created yet, but still allow creating MCQ
    if (!formData.articleId && !id) {
      showToast('Note: MCQ will be created without article link. Create article first to link them.', 'info');
    }
    createMcqMutation.mutate(mcqFormData);
  };

  if (isLoadingItem && isEditMode) {
    return (
      <AdminLayout>
        <div className="flex items-center justify-center h-96">
          <Loader2 className="h-8 w-8 animate-spin text-blue-600" />
        </div>
      </AdminLayout>
    );
  }

  return (
    <>
      <style>{`
        .article-preview-content p {
          margin: 0.5rem 0;
        }
        .article-preview-content p:first-child {
          margin-top: 0;
        }
        .article-preview-content p:last-child {
          margin-bottom: 0;
        }
        .article-preview-content strong,
        .article-preview-content b {
          font-weight: 600;
        }
        .article-preview-content em,
        .article-preview-content i {
          font-style: italic;
        }
        .article-preview-content u {
          text-decoration: underline;
        }
        .article-preview-content a {
          color: #3b82f6;
          text-decoration: underline;
        }
        .article-preview-content ul,
        .article-preview-content ol {
          margin: 0.5rem 0;
          padding-left: 1.5rem;
        }
        .article-preview-content h1,
        .article-preview-content h2,
        .article-preview-content h3,
        .article-preview-content h4,
        .article-preview-content h5,
        .article-preview-content h6 {
          font-weight: 600;
          margin: 0.75rem 0 0.5rem 0;
        }
        .article-preview-content h1 { font-size: 1.5rem; }
        .article-preview-content h2 { font-size: 1.25rem; }
        .article-preview-content h3 { font-size: 1.125rem; }
        .article-preview-content blockquote {
          border-left: 3px solid #cbd5e1;
          padding-left: 1rem;
          margin: 0.5rem 0;
          font-style: italic;
          color: #64748b;
        }
      `}</style>
      <AdminLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button
              variant="ghost"
              onClick={() => navigate('/cms/current-affairs')}
              className="hover:bg-slate-100"
            >
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Current Affairs
            </Button>
            <div>
              <h1 className="text-3xl font-bold text-slate-900">
                {isEditMode ? 'Edit Current Affair' : 'Create Current Affair'}
              </h1>
              <p className="text-slate-600 mt-1">
                {isEditMode ? 'Update current affair details' : 'Add a new current affair article'}
              </p>
            </div>
          </div>
          <Button
            onClick={handleSubmit}
              disabled={createMutation.isPending || updateMutation.isPending || !isDescriptionValid}
            className="bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white font-semibold shadow-lg"
          >
            {(createMutation.isPending || updateMutation.isPending) ? (
              <>
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                {isEditMode ? 'Updating...' : 'Creating...'}
              </>
            ) : (
              <>
                <Save className="h-4 w-4 mr-2" />
                {isEditMode ? 'Update Article' : 'Create Article'}
              </>
            )}
          </Button>
        </div>

        {/* Main Content - Side by Side */}
        <div className="grid gap-6 lg:grid-cols-2">
          {/* Left Side - Form */}
          <Card className="border-0 shadow-xl bg-white">
            <CardHeader className="border-b border-slate-200 bg-gradient-to-r from-blue-50/50 to-white">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-xl bg-gradient-to-br from-blue-500 to-blue-600 shadow-md">
                  <Newspaper className="h-5 w-5 text-white" />
                </div>
                <div>
                  <CardTitle className="text-lg font-bold text-slate-900">Article Details</CardTitle>
                  <CardDescription className="text-slate-600">Enter current affair information</CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent className="pt-6 space-y-6">
              {/* Title */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">Title *</label>
                <Input
                  placeholder="Enter article title"
                  value={formData.title}
                  onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                  className="mt-1"
                />
              </div>

              {/* Description (Max 60 words) */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">
                  Description * (Max 60 words)
                </label>
                <RichTextEditor
                  value={formData.description}
                  onChange={(value) => {
                    // Limit to 60 words
                    const wordCount = getWordCount(value);
                    if (wordCount > 60) {
                      // Truncate to 60 words
                      const parser = new DOMParser();
                      const doc = parser.parseFromString(value, 'text/html');
                      const plainText = doc.body.textContent || doc.body.innerText || '';
                      const words = plainText.trim().split(/\s+/).filter(word => word.length > 0);
                      
                      if (words.length > 60) {
                        const truncatedWords = words.slice(0, 60);
                        const truncatedText = truncatedWords.join(' ');
                        
                        // If original had HTML, try to preserve structure by replacing text content
                        // Otherwise, just use the truncated plain text
                        let truncatedValue = value;
                        if (value.includes('<')) {
                          // Find the text content in the HTML and replace it
                          const body = doc.body;
                          if (body) {
                            body.textContent = truncatedText;
                            truncatedValue = body.innerHTML || truncatedText;
                          } else {
                            truncatedValue = truncatedText;
                          }
                        } else {
                          truncatedValue = truncatedText;
                        }
                        
                        setFormData({ ...formData, description: truncatedValue });
                        showToast('Description limited to 60 words', 'info');
                      } else {
                        setFormData({ ...formData, description: value });
                      }
                    } else {
                      setFormData({ ...formData, description: value });
                    }
                  }}
                  placeholder="Write a brief description (max 60 words) with full formatting options..."
                  minHeight="200px"
                  className="mt-1"
                />
                <div className="mt-2 flex items-center justify-between">
                  <p className={`text-xs ${isDescriptionValid ? 'text-emerald-600' : descriptionWordCount > 60 ? 'text-red-600' : 'text-slate-600'}`}>
                    {descriptionWordCount} / 60 words {descriptionWordCount > 60 && `(Exceeds limit)`}
                  </p>
                  {isDescriptionValid && (
                    <span className="text-xs text-emerald-600 font-semibold">✓ Valid</span>
                  )}
                </div>
              </div>

              {/* Full Article */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">Full Article</label>
                <RichTextEditor
                  value={formData.fullArticle}
                  onChange={(value) => setFormData({ ...formData, fullArticle: value })}
                  placeholder="Write the complete article content with full formatting options..."
                  minHeight="400px"
                  className="mt-1"
                />
                <p className="text-xs text-slate-500 mt-2">
                  Complete article content (optional). Use the toolbar above to format your text (bold, italic, underline, alignment, links, etc.).
                </p>
              </div>

              {/* Category Selection */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">Category *</label>
              <div className="flex items-center gap-2">
                <select
                  value={formData.categoryId}
                  onChange={(e) => handleCategoryChange(e.target.value)}
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                >
                  <option value="">Select Category</option>
                  {categories.map((cat: any) => (
                    <option key={cat.id} value={cat.id}>
                      {cat.name}
                    </option>
                  ))}
                  <option value="__create__">+ Create New Category</option>
                </select>
                <Button variant="outline" size="sm" onClick={() => setIsCategoryDialogOpen(true)}>
                  + Add
                </Button>
              </div>
              </div>

              {/* Sub-Category */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">Sub-Category</label>
              <div className="space-y-2">
                <div className="flex items-center gap-2">
                  <Input
                    placeholder="New sub-category"
                    value={newSubCategory}
                    onChange={(e) => setNewSubCategory(e.target.value)}
                  />
                  <Button variant="outline" size="sm" onClick={handleAddSubCategory} disabled={!newSubCategory.trim()}>
                    Add
                  </Button>
                </div>
                <select
                  value={formData.subCategoryId}
                  onChange={(e) => setFormData({ ...formData, subCategoryId: e.target.value })}
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                >
                  <option value="">Select Sub Category</option>
                  {subCategoryOptions.map((sub) => (
                    <option key={sub} value={sub}>
                      {sub}
                    </option>
                  ))}
                  <option value={formData.subCategoryId || ''}>
                    {formData.subCategoryId ? `Keep: ${formData.subCategoryId}` : 'Custom'}
                  </option>
                </select>
              </div>
              </div>

              {/* Section */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">Section</label>
                <Input
                  placeholder="Enter section"
                  value={formData.section}
                  onChange={(e) => setFormData({ ...formData, section: e.target.value })}
                  className="mt-1"
                />
              </div>

              {/* Country */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">Country</label>
                <Input
                  placeholder="Enter country"
                  value={formData.country}
                  onChange={(e) => setFormData({ ...formData, country: e.target.value })}
                  className="mt-1"
                />
              </div>

              {/* Date */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block flex items-center gap-2">
                  <Calendar className="h-4 w-4" />
                  Article Date
                </label>
                <Input
                  type="date"
                  value={formData.date}
                  onChange={(e) => setFormData({ ...formData, date: e.target.value })}
                  className="mt-1"
                />
                <p className="text-xs text-slate-500 mt-1">
                  The date when this current affair occurred or was published
                </p>
              </div>

              {/* Location */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block flex items-center gap-2">
                  <MapPin className="h-4 w-4" />
                  Location (Latitude & Longitude)
                </label>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="text-xs text-slate-600 mb-1 block">Latitude</label>
                    <Input
                      type="number"
                      step="any"
                      placeholder="e.g., 28.6139"
                      value={formData.location.lat}
                      onChange={(e) => setFormData({
                        ...formData,
                        location: { ...formData.location, lat: e.target.value }
                      })}
                      className="mt-1"
                    />
                  </div>
                  <div>
                    <label className="text-xs text-slate-600 mb-1 block">Longitude</label>
                    <Input
                      type="number"
                      step="any"
                      placeholder="e.g., 77.2090"
                      value={formData.location.long}
                      onChange={(e) => setFormData({
                        ...formData,
                        location: { ...formData.location, long: e.target.value }
                      })}
                      className="mt-1"
                    />
                  </div>
                </div>
                <p className="text-xs text-slate-500 mt-1">
                  Enter the geographical coordinates for this current affair
                </p>
              </div>

              {/* Image Upload */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block flex items-center gap-2">
                  <ImageIcon className="h-4 w-4" />
                  Article Image
                </label>
                
                {formData.imagePreview || formData.imageUrl ? (
                  <div className="mt-2 space-y-3">
                    <div className="relative">
                      <img
                        src={formData.imagePreview || formData.imageUrl}
                        alt="Article preview"
                        className="w-full max-w-md h-48 object-cover rounded-lg border-2 border-slate-200 bg-slate-50"
                        onError={(e) => {
                          (e.target as HTMLImageElement).style.display = 'none';
                        }}
                      />
                      <button
                        type="button"
                        onClick={removeImage}
                        className="absolute top-2 right-2 p-2 bg-red-500 text-white rounded-full hover:bg-red-600 transition-colors shadow-lg"
                      >
                        <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                      </button>
                    </div>
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() => document.getElementById('image-upload')?.click()}
                      className="flex-1"
                    >
                      <ImageIcon className="h-4 w-4 mr-2" />
                      Change Image
                    </Button>
                  </div>
                ) : (
                  <div className="mt-2">
                    <input
                      type="file"
                      id="image-upload"
                      accept="image/*"
                      onChange={handleImageUpload}
                      className="hidden"
                    />
                    <label htmlFor="image-upload">
                      <div className="border-2 border-dashed border-slate-300 rounded-xl p-6 text-center hover:border-blue-400 transition-colors cursor-pointer bg-slate-50 hover:bg-blue-50/50">
                        <div className="flex flex-col items-center gap-3">
                          <div className="p-3 rounded-full bg-blue-100">
                            <ImageIcon className="h-6 w-6 text-blue-600" />
                          </div>
                          <div>
                            <p className="text-sm font-semibold text-slate-900 mb-1">Click to upload image</p>
                            <p className="text-xs text-slate-500">PNG, JPG, GIF up to 5MB</p>
                          </div>
                        </div>
                      </div>
                    </label>
                  </div>
                )}

                {/* Alternative: Image URL */}
                <div className="mt-4 pt-4 border-t border-slate-200">
                  <details className="group">
                    <summary className="text-xs font-medium text-slate-600 cursor-pointer hover:text-slate-900">
                      Or use image URL instead
                    </summary>
                    <div className="mt-2">
                      <Input
                        placeholder="https://example.com/image.jpg"
                        value={formData.imageUrl}
                        onChange={(e) => {
                          if (e.target.value) {
                            setFormData({ 
                              ...formData, 
                              imageUrl: e.target.value,
                              imageFile: null,
                              imagePreview: null,
                            });
                          }
                        }}
                        className="mt-1"
                        disabled={!!formData.imagePreview}
                      />
                    </div>
                  </details>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="space-y-4 pt-4 border-t border-slate-200 mt-6">
                <div className="flex items-center gap-2">
                  <Button
                    type="button"
                    onClick={handleSubmit}
                    disabled={createMutation.isPending || updateMutation.isPending || !isDescriptionValid}
                    className="flex-1 bg-gradient-to-r from-blue-600 to-indigo-600"
                  >
                    {(createMutation.isPending || updateMutation.isPending) ? (
                      <>
                        <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                        {isEditMode ? 'Updating...' : 'Creating...'}
                      </>
                    ) : (
                      <>
                        <Save className="h-4 w-4 mr-2" />
                        {isEditMode ? 'Update Article' : 'Create Article Page'}
                      </>
                    )}
                  </Button>
                  <Button
                    type="button"
                    variant="outline"
                    onClick={handleOpenMcqDialog}
                    className="flex-1"
                  >
                    <HelpCircle className="h-4 w-4 mr-2" />
                    Create MCQ
                  </Button>
                  <Button
                    type="button"
                    variant="destructive"
                    onClick={() => {
                      if (window.confirm('Are you sure you want to reject this article?')) {
                        setFormData(prev => ({ ...prev, isActive: false }));
                        showToast('Article rejected', 'info');
                      }
                    }}
                    className="flex-1"
                  >
                    Reject
                  </Button>
                </div>

                {/* Publish/Deactivate/Send Notification */}
                <div className="grid grid-cols-2 gap-4">
                  <div className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      id="publish-ca"
                      checked={formData.isPublished}
                      onChange={(e) => setFormData({ ...formData, isPublished: e.target.checked })}
                      className="h-4 w-4 text-blue-600 rounded"
                    />
                    <label htmlFor="publish-ca" className="text-sm font-medium text-slate-700 cursor-pointer">
                      Publish
                    </label>
                  </div>
                  <div className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      id="deactivate-ca"
                      checked={!formData.isActive}
                      onChange={(e) => setFormData({ ...formData, isActive: !e.target.checked })}
                      className="h-4 w-4 text-blue-600 rounded"
                    />
                    <label htmlFor="deactivate-ca" className="text-sm font-medium text-slate-700 cursor-pointer">
                      Deactivate
                    </label>
                  </div>
                </div>

                <div className="space-y-2">
                  <div className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      id="sendNotification-ca"
                      checked={formData.sendNotification}
                      onChange={(e) => setFormData({ ...formData, sendNotification: e.target.checked })}
                      className="h-4 w-4 text-blue-600 rounded"
                    />
                    <label htmlFor="sendNotification-ca" className="text-sm font-medium text-slate-700 cursor-pointer">
                      Send Notification
                    </label>
                  </div>
                  {formData.sendNotification && (
                    <div>
                      <label className="text-xs text-slate-600 mb-1 block">Select clock time else current time</label>
                      <Input
                        type="time"
                        value={formData.notificationTime}
                        onChange={(e) => setFormData({ ...formData, notificationTime: e.target.value })}
                        className="w-full"
                      />
                    </div>
                  )}
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Right Side - Live Preview */}
          <Card className="border-0 shadow-xl bg-white sticky top-6">
            <CardHeader className="border-b border-slate-200 bg-gradient-to-r from-emerald-50/50 to-white">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-xl bg-gradient-to-br from-emerald-500 to-emerald-600 shadow-md">
                  <Eye className="h-5 w-5 text-white" />
                </div>
                <div>
                  <CardTitle className="text-lg font-bold text-slate-900">Live Preview</CardTitle>
                  <CardDescription className="text-slate-600">See how your article will appear</CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent className="pt-6">
              <div className="space-y-4">
                {/* Preview Container */}
                <div className="bg-gradient-to-br from-slate-50 to-slate-100 rounded-xl p-6 border-2 border-dashed border-slate-300">
                  <div className="text-center mb-4">
                    <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">
                      Article Preview
                    </p>
                    <div className="w-full h-px bg-slate-200 mb-4"></div>
                  </div>

                  {/* Article Preview Card */}
                  <div className="bg-white rounded-xl shadow-lg overflow-hidden border border-slate-200">
                    {(formData.imagePreview || formData.imageUrl) && (
                      <div className="w-full h-48 bg-slate-100 overflow-hidden">
                        <img
                          src={formData.imagePreview || formData.imageUrl}
                          alt="Article"
                          className="w-full h-full object-cover"
                          onError={(e) => {
                            (e.target as HTMLImageElement).style.display = 'none';
                          }}
                        />
                      </div>
                    )}
                    <div className="p-4 space-y-3">
                      {formData.title ? (
                        <h3 className="text-xl font-bold text-slate-900">{formData.title}</h3>
                      ) : (
                        <div className="h-6 bg-slate-200 rounded animate-pulse"></div>
                      )}
                      {formData.description ? (
                        <div 
                          className="text-sm text-slate-600 line-clamp-4 article-preview-content"
                          style={{ 
                            overflow: 'hidden',
                            display: '-webkit-box',
                            WebkitLineClamp: 4,
                            WebkitBoxOrient: 'vertical'
                          }}
                          dangerouslySetInnerHTML={{ __html: formData.description }}
                        />
                      ) : (
                        <div className="space-y-2">
                          <div className="h-4 bg-slate-200 rounded animate-pulse"></div>
                          <div className="h-4 bg-slate-200 rounded animate-pulse w-5/6"></div>
                          <div className="h-4 bg-slate-200 rounded animate-pulse w-4/6"></div>
                        </div>
                      )}
                      <div className="pt-2 border-t border-slate-200">
                        <div className="flex items-center gap-2 text-xs text-slate-500">
                          <Newspaper className="h-3 w-3" />
                          <span>Current Affairs</span>
                          <span>•</span>
                          <span>{new Date().toLocaleDateString()}</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Preview Info */}
                  <div className="mt-4 p-3 rounded-lg bg-blue-50 border border-blue-200">
                    <p className="text-xs text-blue-800">
                      <strong>Preview Note:</strong> This is how the current affair article will appear to users on the platform.
                    </p>
                  </div>
                </div>

                {/* Preview Status */}
                <div className="space-y-2">
                  <div className="flex items-center justify-between p-3 rounded-lg bg-slate-50 border border-slate-200">
                    <span className="text-sm font-medium text-slate-700">Title Status</span>
                    <span className={`text-xs font-semibold px-2 py-1 rounded-full ${
                      formData.title
                        ? 'bg-emerald-100 text-emerald-700 border border-emerald-200'
                        : 'bg-yellow-100 text-yellow-700 border border-yellow-200'
                    }`}>
                      {formData.title ? '✓ Title Set' : '⚠ Required'}
                    </span>
                  </div>
                  <div className="flex items-center justify-between p-3 rounded-lg bg-slate-50 border border-slate-200">
                    <span className="text-sm font-medium text-slate-700">Content Status</span>
                    <span className={`text-xs font-semibold px-2 py-1 rounded-full ${
                      formData.description
                        ? 'bg-emerald-100 text-emerald-700 border border-emerald-200'
                        : 'bg-yellow-100 text-yellow-700 border border-yellow-200'
                    }`}>
                      {formData.description ? '✓ Content Set' : '⚠ Required'}
                    </span>
                  </div>
                  <div className="flex items-center justify-between p-3 rounded-lg bg-slate-50 border border-slate-200">
                    <span className="text-sm font-medium text-slate-700">Image Status</span>
                    <span className={`text-xs font-semibold px-2 py-1 rounded-full ${
                      formData.imagePreview || formData.imageUrl
                        ? 'bg-emerald-100 text-emerald-700 border border-emerald-200'
                        : 'bg-slate-100 text-slate-600 border border-slate-200'
                    }`}>
                      {formData.imagePreview || formData.imageUrl ? '✓ Image Added' : '○ Optional'}
                    </span>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>

      {/* Create Category Dialog */}
      <Dialog open={isCategoryDialogOpen} onOpenChange={setIsCategoryDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Create Category</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <label className="text-sm font-semibold text-slate-700 mb-2 block">Name</label>
              <Input
                placeholder="Category name"
                value={newCategoryName}
                onChange={(e) => setNewCategoryName(e.target.value)}
              />
            </div>
            <div>
              <label className="text-sm font-semibold text-slate-700 mb-2 block">Description</label>
              <Textarea
                placeholder="Optional description"
                value={newCategoryDescription}
                onChange={(e) => setNewCategoryDescription(e.target.value)}
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsCategoryDialogOpen(false)}>
              Cancel
            </Button>
            <Button
              onClick={() =>
                createCategoryMutation.mutate({
                  name: newCategoryName,
                  description: newCategoryDescription,
                })
              }
              disabled={createCategoryMutation.isPending || !newCategoryName.trim()}
              className="bg-gradient-to-r from-blue-600 to-indigo-600"
            >
              {createCategoryMutation.isPending ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Creating...
                </>
              ) : (
                'Create'
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Create MCQ Dialog */}
      <Dialog open={isMcqDialogOpen} onOpenChange={setIsMcqDialogOpen}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center justify-between">
              <span>Create MCQ Questions</span>
              <Button
                variant="ghost"
                size="sm"
                onClick={handleCloseMcqDialog}
                className="h-6 w-6 p-0"
              >
                <X className="h-4 w-4" />
              </Button>
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-6">
            {/* Warning if article not created */}
            {!formData.articleId && !id && (
              <div className="p-3 rounded-lg bg-yellow-50 border border-yellow-200">
                <p className="text-sm text-yellow-800">
                  <strong>Note:</strong> The article hasn't been created yet. MCQs will be created without an article link. Create the article first to automatically link them.
                </p>
              </div>
            )}
            {/* Created MCQs List */}
            {createdMcqs.length > 0 && (
              <div className="border border-slate-200 rounded-lg p-4 bg-slate-50">
                <h3 className="text-sm font-semibold text-slate-700 mb-3">
                  Created MCQs ({createdMcqs.length})
                </h3>
                <div className="space-y-2 max-h-40 overflow-y-auto">
                  {createdMcqs.map((mcq, idx) => (
                    <div key={mcq.id || idx} className="flex items-center justify-between p-2 bg-white rounded border border-slate-200">
                      <div className="flex-1">
                        <p className="text-sm font-medium text-slate-900 line-clamp-1">
                          {mcq.question || `MCQ ${idx + 1}`}
                        </p>
                      </div>
                      <CheckCircle2 className="h-4 w-4 text-emerald-600 ml-2" />
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* MCQ Form */}
            <div className="space-y-4">
              {/* Category */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">Category</label>
                <select
                  value={mcqFormData.categoryId}
                  onChange={(e) => setMcqFormData({ ...mcqFormData, categoryId: e.target.value })}
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                >
                  <option value="">Select a category</option>
                  {mcqCategories.map((cat: any) => (
                    <option key={cat.id} value={cat.id}>
                      {cat.name}
                    </option>
                  ))}
                </select>
              </div>

              {/* Question */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">Question *</label>
                <Textarea
                  placeholder="Enter the question..."
                  value={mcqFormData.question}
                  onChange={(e) => setMcqFormData({ ...mcqFormData, question: e.target.value })}
                  className="min-h-[100px]"
                  rows={4}
                />
              </div>

              {/* Options */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">Answer Options *</label>
                <div className="space-y-3">
                  {mcqFormData.options.map((option, index) => (
                    <div key={index} className="flex items-center gap-3">
                      <div className={`flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center font-bold text-sm ${
                        mcqFormData.correctAnswer === index
                          ? 'bg-emerald-500 text-white'
                          : 'bg-slate-200 text-slate-600'
                      }`}>
                        {String.fromCharCode(65 + index)}
                      </div>
                      <Input
                        placeholder={`Option ${String.fromCharCode(65 + index)}`}
                        value={option}
                        onChange={(e) => updateMcqOption(index, e.target.value)}
                        className="flex-1"
                      />
                      <Button
                        type="button"
                        variant={mcqFormData.correctAnswer === index ? 'default' : 'outline'}
                        size="sm"
                        onClick={() => setMcqFormData({ ...mcqFormData, correctAnswer: index })}
                        className={mcqFormData.correctAnswer === index ? 'bg-emerald-600 hover:bg-emerald-700' : ''}
                      >
                        {mcqFormData.correctAnswer === index ? (
                          <CheckCircle2 className="h-4 w-4" />
                        ) : (
                          <XCircle className="h-4 w-4" />
                        )}
                      </Button>
                    </div>
                  ))}
                </div>
                <p className="text-xs text-slate-500 mt-2">Click the checkmark to mark the correct answer</p>
              </div>

              {/* Explanation */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">Explanation (Optional)</label>
                <Textarea
                  placeholder="Explain why this is the correct answer..."
                  value={mcqFormData.explanation}
                  onChange={(e) => setMcqFormData({ ...mcqFormData, explanation: e.target.value })}
                  className="min-h-[80px]"
                  rows={4}
                />
              </div>
            </div>
          </div>
          <DialogFooter className="flex items-center justify-between">
            <div className="text-sm text-slate-600">
              {createdMcqs.length > 0 && (
                <span className="text-emerald-600 font-medium">
                  {createdMcqs.length} MCQ{createdMcqs.length !== 1 ? 's' : ''} created
                </span>
              )}
            </div>
            <div className="flex gap-2">
              <Button
                variant="outline"
                onClick={handleCloseMcqDialog}
              >
                Done
              </Button>
              <Button
                onClick={handleCreateMcq}
                disabled={createMcqMutation.isPending}
                className="bg-gradient-to-r from-blue-600 to-indigo-600"
              >
                {createMcqMutation.isPending ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Creating...
                  </>
                ) : (
                  <>
                    <Plus className="h-4 w-4 mr-2" />
                    Add MCQ
                  </>
                )}
              </Button>
            </div>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </AdminLayout>
    </>
  );
}

