import { useState, useEffect, useRef } from 'react';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { AdminLayout } from '../../components/layout/AdminLayout';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../components/ui/card';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { Textarea } from '../../components/ui/textarea';
import { RichTextEditor } from '../../components/ui/RichTextEditor';
import { ArrowLeft, Save, Eye, Newspaper, Loader2, Image as ImageIcon, HelpCircle, CheckCircle2, XCircle, Plus, X, Calendar, MapPin, Tag, Send, Cloud, CloudOff } from 'lucide-react';
import { useToast } from '../../contexts/ToastContext';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { cmsApi, Chapter } from '../../services/api/cms';
import { postsApi } from '../../services/api/posts';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '../../components/ui/dialog';
import { useAutoSave } from '../../hooks/useAutoSave';

export default function CreateCurrentAffairPage() {
  const navigate = useNavigate();
  const { id } = useParams<{ id?: string }>();
  const [searchParams] = useSearchParams();
  const isEditMode = !!id;
  const { showToast } = useToast();
  const queryClient = useQueryClient();

  // Category and sub-category creation removed - use Wall Categories in dashboard instead
  
  // MCQ Dialog state
  const [isMcqDialogOpen, setIsMcqDialogOpen] = useState(false);
  const [mcqFormData, setMcqFormData] = useState({
    question: '',
    options: ['', '', '', ''],
    correctAnswer: 0,
    categoryId: '',
    subCategoryId: '',
    chapterId: '',
    explanation: '',
    explanationImageFile: null as File | null,
    explanationImagePreview: null as string | null,
    explanationImageUrl: '',
  });
  const [createdMcqs, setCreatedMcqs] = useState<any[]>([]);

  const [formData, setFormData] = useState({
    title: '',
    description: '',
    fullArticle: '',
    category: '',
    subCategory: '',
    categoryId: '',
    subCategoryId: '',
    chapterId: '',
    section: '',
    country: '',
    imageUrl: '',
    imageFile: null as File | null,
    imagePreview: null as string | null,
    // New fields
    postType: 'Current Affairs',
    targetedKeywords: '',
    autoGeneratedKeywords: '',
    date: '', // Event date
    eventDates: [] as Array<{ date: string; title: string }>, // Array of notification dates with titles
    eventYearRange: '',
    location: {
      lat: '',
      long: '',
    },
    state: '',
    district: '',
    city: '',
    language: 'ENGLISH', // Language tag: ENGLISH or HINDI
    isPublished: false,
    isActive: true,
    sendNotification: false,
    notificationTime: '', // Clock time for notification
    articleId: '', // For linking MCQ
  });

  // Fetch categories (top-level categories using new cascading endpoint)
  const { data: categoriesData } = useQuery({
    queryKey: ['ca-categories'],
    queryFn: () => cmsApi.getCategories('current-affairs'),
  });

  const categories = categoriesData || [];

  // Fetch sub-categories for the selected category (using new cascading endpoint)
  const { data: subCategoriesData } = useQuery({
    queryKey: ['ca-subcategories', formData.categoryId],
    queryFn: () =>
      formData.categoryId ? cmsApi.getSubCategories(formData.categoryId, 'current-affairs') : [],
    enabled: !!formData.categoryId,
  });

  const subCategories = subCategoriesData || [];

  // Initialize form data from URL params if provided (for creating from sub-category page)
  useEffect(() => {
    if (!isEditMode) {
      const categoryIdParam = searchParams.get('categoryId');
      const subCategoryIdParam = searchParams.get('subCategoryId');
      if (categoryIdParam || subCategoryIdParam) {
        setFormData(prev => ({
          ...prev,
          categoryId: categoryIdParam || prev.categoryId,
          subCategoryId: subCategoryIdParam || prev.subCategoryId,
        }));
      }
    }
  }, [searchParams, isEditMode]);

  // Fetch chapters (sections) for the selected sub-category (using new cascading endpoint)
  const { data: chaptersData } = useQuery<Chapter[]>({
    queryKey: ['ca-chapters', formData.subCategoryId],
    queryFn: () =>
      formData.subCategoryId ? cmsApi.getChaptersBySubCategoryNew(formData.subCategoryId, 'current-affairs') : [],
    enabled: !!formData.subCategoryId,
  });

  const chapters = chaptersData || [];

  // Fetch sub-categories for the selected MCQ category (in dialog) - using new cascading endpoint
  const { data: mcqSubCategoriesData } = useQuery({
    queryKey: ['ca-mcq-subcategories', mcqFormData.categoryId],
    queryFn: () =>
      mcqFormData.categoryId ? cmsApi.getSubCategories(mcqFormData.categoryId, 'current-affairs') : [],
    enabled: !!mcqFormData.categoryId,
  });

  const mcqSubCategories = mcqSubCategoriesData || [];

  // Fetch chapters for the selected MCQ sub-category (in dialog) - using new cascading endpoint
  const { data: mcqChaptersData } = useQuery<Chapter[]>({
    queryKey: ['ca-mcq-chapters', mcqFormData.subCategoryId],
    queryFn: () =>
      mcqFormData.subCategoryId ? cmsApi.getChaptersBySubCategoryNew(mcqFormData.subCategoryId, 'current-affairs') : [],
    enabled: !!mcqFormData.subCategoryId,
  });

  const mcqChapters = mcqChaptersData || [];

  // Sub-category options removed - sub-categories are now simple text input

  // Calculate word count for description (handles HTML content)
  // Uses DOMParser to safely extract text without executing scripts
  const getWordCount = (text: string) => {
    if (!text) return 0;
    try {
      // Use DOMParser to safely parse HTML without executing scripts
      const parser = new DOMParser();
      const doc = parser.parseFromString(text, 'text/html');
      const plainText = doc.body.textContent || doc.body.innerText || '';
      return plainText.trim().split(/\s+/).filter(word => word.length > 0).length;
    } catch (error) {
      // Fallback: strip HTML tags using regex if DOMParser fails
      const plainText = text.replace(/<[^>]*>/g, '').replace(/&[^;]+;/g, ' ');
      return plainText.trim().split(/\s+/).filter(word => word.length > 0).length;
    }
  };

  const getCharacterCount = (text: string) => {
    if (!text) return 0;
    try {
      // Use DOMParser to safely parse HTML without executing scripts
      const parser = new DOMParser();
      const doc = parser.parseFromString(text, 'text/html');
      const plainText = doc.body.textContent || doc.body.innerText || '';
      return plainText.length;
    } catch (error) {
      // Fallback: strip HTML tags using regex if DOMParser fails
      const plainText = text.replace(/<[^>]*>/g, '').replace(/&[^;]+;/g, ' ');
      return plainText.length;
    }
  };

  const descriptionWordCount = getWordCount(formData.description);
  const isDescriptionValid = descriptionWordCount > 0;

  // Auto-save functionality (only in create mode, not edit mode)
  const autoSaveKey = `cms-draft-current-affair-${id || 'new'}`;
  const { isSaving, lastSaved, hasDraft, restoreDraft, clearDraft } = useAutoSave({
    key: autoSaveKey,
    data: formData,
    enabled: !isEditMode, // Only auto-save in create mode
    debounceMs: 2000, // Save 2 seconds after last change
    onRestore: (restoredData) => {
      // Only restore if we're in create mode and form is empty
      if (!isEditMode && !formData.title && !formData.description) {
        // Restore image preview if it was a data URL
        if (restoredData.imagePreview && restoredData.imagePreview.startsWith('data:')) {
          setFormData(restoredData);
        } else {
          // Clear imagePreview if it's not a data URL (can't restore File objects)
          setFormData({ ...restoredData, imageFile: null, imagePreview: null });
        }
        showToast('Draft restored from auto-save', 'info');
      }
    },
  });

  // Restore draft on mount if in create mode
  useEffect(() => {
    if (!isEditMode && hasDraft) {
      const restored = restoreDraft();
      if (restored && !formData.title && !formData.description) {
        // Show restore prompt
        if (window.confirm('A draft was found. Would you like to restore it?')) {
          if (restored.imagePreview && restored.imagePreview.startsWith('data:')) {
            setFormData(restored);
          } else {
            setFormData({ ...restored, imageFile: null, imagePreview: null });
          }
          showToast('Draft restored', 'success');
        } else {
          clearDraft();
        }
      }
    }
  }, []); // Only run on mount

  // Category creation removed - use Wall Categories in dashboard instead

  // Fetch existing item if editing
  const { data: existingItem, isLoading: isLoadingItem, error: existingItemError } = useQuery({
    queryKey: ['current-affair', id],
    queryFn: async () => {
      if (!id) return null;
      try {
        console.log('Fetching current affair item with ID:', id);
        const item = await cmsApi.getCurrentAffairById(id);
        console.log('Fetched item:', item);
        return item || null;
      } catch (error) {
        console.error('Error fetching current affair item:', error);
        return null;
      }
    },
    enabled: isEditMode && !!id,
    staleTime: 0, // Always fetch fresh data when editing
  });

  // Track previous ID to only reset when ID actually changes
  const prevIdRef = useRef<string | undefined>(undefined);
  // Track if data has been loaded to prevent reset after load and force RichTextEditor remount
  const [dataLoadedKey, setDataLoadedKey] = useState<string>('initial');

  // Reset form when ID changes (switching between edit/create modes or different items)
  useEffect(() => {
    // Only reset if ID actually changed and we're entering edit mode
    if (isEditMode && id && id !== prevIdRef.current) {
      prevIdRef.current = id;
      setDataLoadedKey('initial'); // Reset the data loaded key
      // Reset form when entering edit mode with a new ID
      setFormData({
        title: '',
        description: '',
        fullArticle: '',
        category: '',
        subCategory: '',
        categoryId: '',
        subCategoryId: '',
        chapterId: '',
        section: '',
        country: '',
        imageUrl: '',
        imageFile: null,
        imagePreview: null,
        postType: 'Current Affairs',
        targetedKeywords: '',
        autoGeneratedKeywords: '',
        date: '',
        eventDates: [],
        eventYearRange: '',
        location: { lat: '', long: '' },
        state: '',
        district: '',
        city: '',
        language: 'ENGLISH',
        isPublished: false,
        isActive: true,
        sendNotification: false,
        notificationTime: '',
        articleId: '',
      });
    } else if (!isEditMode) {
      // Reset ref when leaving edit mode
      prevIdRef.current = undefined;
      setDataLoadedKey('initial');
    }
  }, [id, isEditMode]);

  // Update form when existing item loads
  // This should run after existingItem is loaded and only in edit mode
  useEffect(() => {
    if (existingItem && isEditMode && !isLoadingItem && typeof existingItem === 'object' && dataLoadedKey === 'initial') {
      console.log('Loading existing item for edit:', existingItem);
      const item = existingItem as any;
      
      // Read from top level (new structure) or metadata (backward compatibility)
      const metadata = item.metadata || {};
      
      // Language can be at top level or in metadata (backward compatibility)
      const language = item.language || metadata.language || 'ENGLISH';
      
      // Location: read from locationLat/locationLong (new) or location object (old)
      let location = { lat: '', long: '' };
      if (item.locationLat || item.locationLong) {
        // New structure: flattened fields
        location = {
          lat: item.locationLat || '',
          long: item.locationLong || '',
        };
      } else if (metadata.location || item.location) {
        // Old structure: nested object (backward compatibility)
        const loc = metadata.location || item.location;
        if (typeof loc === 'object' && loc !== null) {
          location = {
            lat: loc.lat || loc.latitude || '',
            long: loc.long || loc.longitude || '',
          };
        }
      }
      
      // Event dates: read from top level or metadata
      // Support both old format (string[]) and new format (Array<{date, title}>)
      let eventDates: Array<{ date: string; title: string }> = [];
      if (item.eventDates) {
        if (Array.isArray(item.eventDates)) {
          // Check if it's new format (objects) or old format (strings)
          if (item.eventDates.length > 0 && typeof item.eventDates[0] === 'object' && item.eventDates[0] !== null) {
            eventDates = item.eventDates as Array<{ date: string; title: string }>;
          } else {
            // Old format: convert strings to objects
            eventDates = (item.eventDates as string[]).map(date => ({ date, title: '' }));
          }
        }
      } else if (metadata.eventDates) {
        if (Array.isArray(metadata.eventDates)) {
          // Check if it's new format (objects) or old format (strings)
          if (metadata.eventDates.length > 0 && typeof metadata.eventDates[0] === 'object' && metadata.eventDates[0] !== null) {
            eventDates = metadata.eventDates as Array<{ date: string; title: string }>;
          } else {
            // Old format: convert strings to objects
            eventDates = (metadata.eventDates as string[]).map(date => ({ date, title: '' }));
          }
        } else if (typeof metadata.eventDates === 'string') {
          try {
            const parsed = JSON.parse(metadata.eventDates);
            if (Array.isArray(parsed)) {
              if (parsed.length > 0 && typeof parsed[0] === 'object' && parsed[0] !== null) {
                eventDates = parsed as Array<{ date: string; title: string }>;
              } else {
                eventDates = (parsed as string[]).map(date => ({ date, title: '' }));
              }
            }
          } catch {
            eventDates = [];
          }
        }
      }
      
      // Date: read from articleDate (new) or date (old)
      const date = item.articleDate || metadata.date || item.date || '';
      
      // Category: read from articleCategory (new) or category (old)
      const category = item.articleCategory || metadata.category || item.category || '';
      
      const formDataToSet = {
        title: item.title || '',
        description: item.description || '',
        fullArticle: item.fullArticle || metadata.fullArticle || '',
        category: category,
        subCategory: item.subCategory || metadata.subCategory || '',
        categoryId: item.categoryId || '',
        subCategoryId: item.subCategoryId || metadata.subCategoryId || '',
        chapterId: item.chapterId || metadata.chapterId || '',
        section: item.section || metadata.section || '',
        country: item.country || metadata.country || '',
        imageUrl: item.images?.[0] || '',
        imageFile: null,
        imagePreview: item.images?.[0] || null,
        postType: item.postType || metadata.postType || 'Current Affairs',
        targetedKeywords: item.targetedKeywords || metadata.targetedKeywords || '',
        autoGeneratedKeywords: item.autoGeneratedKeywords || metadata.autoGeneratedKeywords || '',
        language: language,
        date: date,
        eventDates: eventDates,
        eventYearRange: item.eventYearRange || metadata.eventYearRange || '',
        location: location,
        state: item.state || metadata.state || '',
        district: item.district || metadata.district || '',
        city: item.city || metadata.city || '',
        isPublished: item.isPublished || false,
        isActive: item.isActive !== false,
        sendNotification: item.sendNotification !== undefined ? item.sendNotification : (metadata.sendNotification || false),
        notificationTime: item.notificationTime || metadata.notificationTime || '',
        articleId: item.id || '',
      };
      
      console.log('Setting form data:', formDataToSet);
      setFormData(formDataToSet);
      setDataLoadedKey(item.id || 'loaded'); // Mark data as loaded and trigger RichTextEditor remount
      console.log('Form data has been set. Current formData state:', formDataToSet);
    }
  }, [existingItem, isEditMode, isLoadingItem, dataLoadedKey]);

  // Handle image file selection
  const handleImageUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      if (!file.type.startsWith('image/')) {
        showToast('Please select an image file', 'error');
        return;
      }
      if (file.size > 5 * 1024 * 1024) {
        showToast('Image size should be less than 5MB', 'error');
        return;
      }
      const reader = new FileReader();
      reader.onloadend = () => {
        setFormData(prev => ({
          ...prev,
          imageFile: file,
          imagePreview: reader.result as string,
          imageUrl: '',
        }));
      };
      reader.readAsDataURL(file);
    }
  };

  const removeImage = () => {
    setFormData(prev => ({
      ...prev,
      imageFile: null,
      imagePreview: null,
      imageUrl: '',
    }));
  };

  const createMutation = useMutation({
    mutationFn: (data: typeof formData) => {
      const imageUrl = data.imagePreview || data.imageUrl;
      
      // Helper to clean empty strings and undefined values
      const cleanValue = (value: any) => {
        if (value === '' || value === null) return undefined;
        if (Array.isArray(value) && value.length === 0) return undefined;
        return value;
      };
      
      // Build payload with all fields at top level (no metadata object)
      const payload: any = {
        title: data.title,
        description: data.description,
        categoryId: data.categoryId || undefined,
        images: imageUrl ? [imageUrl] : [],
        isPublished: data.isPublished,
        language: data.language || 'ENGLISH',
        fullArticle: cleanValue(data.fullArticle),
        articleCategory: cleanValue(data.category), // Renamed from 'category'
        subCategoryId: cleanValue(data.subCategoryId),
        subCategory: cleanValue(data.subCategory),
        chapterId: cleanValue(data.chapterId),
        section: cleanValue(data.section),
        country: cleanValue(data.country),
        articleDate: cleanValue(data.date), // Renamed from 'date'
        eventDates: data.eventDates && data.eventDates.length > 0 ? data.eventDates : undefined,
        eventYearRange: cleanValue(data.eventYearRange),
        locationLat: cleanValue(data.location?.lat), // Flattened from location object
        locationLong: cleanValue(data.location?.long), // Flattened from location object
        state: cleanValue(data.state),
        district: cleanValue(data.district),
        city: cleanValue(data.city),
        targetedKeywords: cleanValue(data.targetedKeywords),
        autoGeneratedKeywords: cleanValue(data.autoGeneratedKeywords),
        sendNotification: data.sendNotification !== undefined ? data.sendNotification : undefined,
        notificationTime: cleanValue(data.notificationTime),
      };
      
      // Remove undefined values
      Object.keys(payload).forEach(key => {
        if (payload[key] === undefined) {
          delete payload[key];
        }
      });
      
      // Log payload for debugging
      console.log('Creating current affair with payload:', JSON.stringify(payload, null, 2));
      
      return cmsApi.createCurrentAffair(payload);
    },
    onSuccess: (response) => {
      queryClient.invalidateQueries({ queryKey: ['current-affairs'] });
      const createdArticle = Array.isArray(response) ? response[0] : response;
      const articleId = createdArticle?.id;
      if (articleId) {
        setFormData(prev => ({ ...prev, articleId }));
      }
      clearDraft(); // Clear draft when successfully published
      showToast('Current affair created successfully', 'success');
      // Navigate to all articles page after successful creation
      navigate('/cms/current-affairs');
    },
    onError: (error: any) => {
      // Log full error details for debugging
      const requestPayload = error?.config?.data ? JSON.parse(error.config.data) : null;
      const errorResponse = error?.response?.data;
      
      console.error('Create current affair error:', {
        error,
        response: error?.response,
        responseData: errorResponse,
        requestData: requestPayload,
        fullErrorResponse: JSON.stringify(errorResponse, null, 2),
      });
      
      // Also log the error details structure
      if (errorResponse?.error?.details) {
        console.error('Error details:', errorResponse.error.details);
      }
      if (errorResponse?.error?.message) {
        console.error('Error message:', errorResponse.error.message);
      }
      
      // Extract error message from various possible structures
      let errorMessage = 'Failed to create current affair';
      
      if (error?.response?.data) {
        const responseData = error.response.data;
        
        // Handle backend error structure: { success: false, error: { code, message, details: { message: [...] } } }
        if (responseData.error) {
          const errorObj = responseData.error;
          
          // First try error.message
          if (errorObj.message && typeof errorObj.message === 'string') {
            errorMessage = errorObj.message;
          }
          // Then try error.details.message array
          else if (errorObj.details?.message) {
            if (Array.isArray(errorObj.details.message)) {
              errorMessage = errorObj.details.message
                .filter((msg: any) => typeof msg === 'string')
                .join(', ');
            } else if (typeof errorObj.details.message === 'string') {
              errorMessage = errorObj.details.message;
            }
          }
          // Fallback to error.details if it's a string
          else if (errorObj.details && typeof errorObj.details === 'string') {
            errorMessage = errorObj.details;
          }
        }
        // Handle direct message property
        else if (responseData.message && typeof responseData.message === 'string') {
          errorMessage = responseData.message;
        }
        // Handle details property directly
        else if (responseData.details) {
          if (Array.isArray(responseData.details)) {
            errorMessage = responseData.details
              .map((detail: any) => {
                if (typeof detail === 'string') return detail;
                if (detail?.message) return detail.message;
                return JSON.stringify(detail);
              })
              .join(', ');
          } else if (typeof responseData.details === 'string') {
            errorMessage = responseData.details;
          } else if (responseData.details.message) {
            if (Array.isArray(responseData.details.message)) {
              errorMessage = responseData.details.message.join(', ');
            } else {
              errorMessage = responseData.details.message;
            }
          }
        }
        // Handle string response
        else if (typeof responseData === 'string') {
          errorMessage = responseData;
        }
        // Handle array response
        else if (Array.isArray(responseData)) {
          errorMessage = responseData
            .map((err: any) => err.message || JSON.stringify(err))
            .join(', ');
        }
        // Last resort
        else {
          errorMessage = 'Validation error. Check console for details.';
        }
      } else if (error?.message) {
        errorMessage = error.message;
      }
      
      // Ensure we always have a string (never pass an object to showToast)
      if (typeof errorMessage !== 'string') {
        errorMessage = String(errorMessage);
      }
      
      // Limit message length to avoid UI issues
      if (errorMessage.length > 200) {
        errorMessage = errorMessage.substring(0, 200) + '...';
      }
      
      showToast(errorMessage, 'error');
    },
  });

  const updateMutation = useMutation({
    mutationFn: (data: typeof formData) => {
      const imageUrl = data.imagePreview || data.imageUrl;
      
      // Helper to clean empty strings and undefined values
      const cleanValue = (value: any) => {
        if (value === '' || value === null) return undefined;
        if (Array.isArray(value) && value.length === 0) return undefined;
        return value;
      };
      
      // Build payload with all fields at top level (no metadata object)
      const payload: any = {
        title: data.title,
        description: data.description,
        categoryId: data.categoryId || undefined,
        images: imageUrl ? [imageUrl] : [],
        isPublished: data.isPublished,
        language: data.language || 'ENGLISH',
        fullArticle: cleanValue(data.fullArticle),
        articleCategory: cleanValue(data.category), // Renamed from 'category'
        subCategoryId: cleanValue(data.subCategoryId),
        subCategory: cleanValue(data.subCategory),
        chapterId: cleanValue(data.chapterId),
        section: cleanValue(data.section),
        country: cleanValue(data.country),
        articleDate: cleanValue(data.date), // Renamed from 'date'
        eventDates: data.eventDates && data.eventDates.length > 0 ? data.eventDates : undefined,
        eventYearRange: cleanValue(data.eventYearRange),
        locationLat: cleanValue(data.location?.lat), // Flattened from location object
        locationLong: cleanValue(data.location?.long), // Flattened from location object
        state: cleanValue(data.state),
        district: cleanValue(data.district),
        city: cleanValue(data.city),
        targetedKeywords: cleanValue(data.targetedKeywords),
        autoGeneratedKeywords: cleanValue(data.autoGeneratedKeywords),
        sendNotification: data.sendNotification !== undefined ? data.sendNotification : undefined,
        notificationTime: cleanValue(data.notificationTime),
      };
      
      // Remove undefined values
      Object.keys(payload).forEach(key => {
        if (payload[key] === undefined) {
          delete payload[key];
        }
      });
      
      return cmsApi.updateCurrentAffair(id!, payload);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['current-affairs'] });
      queryClient.invalidateQueries({ queryKey: ['current-affair', id] });
      showToast('Current affair updated successfully', 'success');
      navigate('/cms/current-affairs');
    },
    onError: () => showToast('Failed to update current affair', 'error'),
  });

  const handlePublish = () => {
    if (!formData.title.trim()) {
      showToast('Please enter a title', 'error');
      return;
    }
    if (!formData.description.trim()) {
      showToast('Please enter a description', 'error');
      return;
    }

    const publishData = { ...formData, isPublished: true };
    if (isEditMode) {
      updateMutation.mutate(publishData);
    } else {
      createMutation.mutate(publishData);
    }
  };

  const handleCategoryChange = (value: string) => {
    const selectedCategory = categories.find((cat: any) => cat.id === value);
    setFormData(prev => ({
      ...prev,
      categoryId: value,
      category: selectedCategory?.name || prev.category,
      subCategoryId: '',
      subCategory: '',
    }));
  };

  // MCQ Dialog handlers
  const handleOpenMcqDialog = () => {
    // Auto-populate category, sub-category, and chapter from article
    setMcqFormData(prev => ({
      ...prev,
      categoryId: formData.categoryId || '',
      subCategoryId: formData.subCategoryId || '',
      chapterId: formData.chapterId || '',
    }));
    setIsMcqDialogOpen(true);
  };

  const handleCloseMcqDialog = () => {
    setIsMcqDialogOpen(false);
    // Reset form and created MCQs list when closing
    setMcqFormData({
      question: '',
      options: ['', '', '', ''],
      correctAnswer: 0,
      categoryId: '',
      subCategoryId: '',
      chapterId: '',
      explanation: '',
      explanationImageFile: null,
      explanationImagePreview: null,
      explanationImageUrl: '',
    });
    setCreatedMcqs([]);
  };

  const updateMcqOption = (index: number, value: string) => {
    const newOptions = [...mcqFormData.options];
    newOptions[index] = value;
    setMcqFormData({ ...mcqFormData, options: newOptions });
  };

  // Handle MCQ explanation image upload
  const handleMcqExplanationImageUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      if (!file.type.startsWith('image/')) {
        showToast('Please select an image file', 'error');
        return;
      }
      if (file.size > 5 * 1024 * 1024) {
        showToast('Image size should be less than 5MB', 'error');
        return;
      }
      const reader = new FileReader();
      reader.onloadend = () => {
        setMcqFormData(prev => ({
          ...prev,
          explanationImageFile: file,
          explanationImagePreview: reader.result as string,
          explanationImageUrl: '',
        }));
      };
      reader.readAsDataURL(file);
    }
  };

  const removeMcqExplanationImage = () => {
    setMcqFormData(prev => ({
      ...prev,
      explanationImageFile: null,
      explanationImagePreview: null,
      explanationImageUrl: '',
    }));
  };

  const createMcqMutation = useMutation({
    mutationFn: (data: typeof mcqFormData) => {
      const articleId = formData.articleId || id;
      const explanationImage = data.explanationImagePreview || data.explanationImageUrl;
      // Build payload with all fields at top level (no metadata object)
      const payload: any = {
        question: data.question,
        options: data.options.map((opt, idx) => ({
          text: opt,
          isCorrect: idx === data.correctAnswer,
        })),
        correctAnswer: data.correctAnswer,
        categoryId: data.categoryId || undefined,
        explanation: data.explanation || undefined,
        explanationImage: explanationImage || undefined,
        articleId: articleId || undefined,
        subCategoryId: data.subCategoryId || undefined, // At top level, not in metadata
        chapterId: data.chapterId || undefined, // At top level, not in metadata
      };
      
      // Remove undefined values
      Object.keys(payload).forEach(key => {
        if (payload[key] === undefined) {
          delete payload[key];
        }
      });
      
      return cmsApi.createMcqQuestion(payload);
    },
    onSuccess: async (response) => {
      // Invalidate all MCQ queries to ensure they appear in the MCQ page
      await queryClient.invalidateQueries({ queryKey: ['mcq-questions'] });
      // Also refetch to ensure immediate visibility
      await queryClient.refetchQueries({ queryKey: ['mcq-questions'] });
      const createdMcq = Array.isArray(response) ? response[0] : response;
      setCreatedMcqs(prev => [...prev, createdMcq]);
      showToast('MCQ question published successfully', 'success');
      // Close the dialog after successful creation
      setIsMcqDialogOpen(false);
      // Reset form
      setMcqFormData({
        question: '',
        options: ['', '', '', ''],
        correctAnswer: 0,
        categoryId: '',
        subCategoryId: '',
        chapterId: '',
        explanation: '',
        explanationImageFile: null,
        explanationImagePreview: null,
        explanationImageUrl: '',
      });
      setCreatedMcqs([]);
    },
    onError: () => showToast('Failed to create MCQ question', 'error'),
  });

  const handleCreateMcq = () => {
    if (!mcqFormData.question.trim()) {
      showToast('Please enter a question', 'error');
      return;
    }
    if (mcqFormData.options.filter(opt => opt.trim()).length < 2) {
      showToast('Please provide at least 2 options', 'error');
      return;
    }
    if (mcqFormData.correctAnswer < 0 || mcqFormData.correctAnswer >= mcqFormData.options.length) {
      showToast('Please select a valid correct answer', 'error');
      return;
    }
    // Warn if article not created yet, but still allow creating MCQ
    if (!formData.articleId && !id) {
      showToast('Note: MCQ will be created without article link. Create article first to link them.', 'info');
    }
    createMcqMutation.mutate(mcqFormData);
  };

  if (isLoadingItem && isEditMode) {
    return (
      <AdminLayout>
        <div className="flex items-center justify-center h-96">
          <Loader2 className="h-8 w-8 animate-spin text-blue-600" />
        </div>
      </AdminLayout>
    );
  }

  return (
    <>
      <style>{`
        .description-editor .ql-editor {
          padding: 0.5rem !important;
          min-height: 60px !important;
        }
        .description-editor .ql-container {
          min-height: 60px !important;
        }
        .article-preview-content p {
          margin: 0.5rem 0;
        }
        .article-preview-content p:first-child {
          margin-top: 0;
        }
        .article-preview-content p:last-child {
          margin-bottom: 0;
        }
        .article-preview-content strong,
        .article-preview-content b {
          font-weight: 600;
        }
        .article-preview-content em,
        .article-preview-content i {
          font-style: italic;
        }
        .article-preview-content u {
          text-decoration: underline;
        }
        .article-preview-content a {
          color: #3b82f6;
          text-decoration: underline;
        }
        .article-preview-content ul,
        .article-preview-content ol {
          margin: 0.5rem 0;
          padding-left: 1.5rem;
        }
        .article-preview-content h1,
        .article-preview-content h2,
        .article-preview-content h3,
        .article-preview-content h4,
        .article-preview-content h5,
        .article-preview-content h6 {
          font-weight: 600;
          margin: 0.75rem 0 0.5rem 0;
        }
        .article-preview-content h1 { font-size: 1.5rem; }
        .article-preview-content h2 { font-size: 1.25rem; }
        .article-preview-content h3 { font-size: 1.125rem; }
        .article-preview-content blockquote {
          border-left: 3px solid #cbd5e1;
          padding-left: 1rem;
          margin: 0.5rem 0;
          font-style: italic;
          color: #64748b;
        }
      `}</style>
      <AdminLayout>
      <div className="space-y-6">
        {/* Auto-save indicator */}
        {!isEditMode && (
          <div className="flex items-center justify-between bg-slate-50 p-3 rounded-lg border border-slate-200">
            <div className="flex items-center gap-2 text-sm text-slate-600">
              {isSaving ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" />
                  <span>Saving draft...</span>
                </>
              ) : hasDraft && lastSaved ? (
                <>
                  <Cloud className="h-4 w-4 text-green-600" />
                  <span>Draft saved {lastSaved.toLocaleTimeString()}</span>
                </>
              ) : (
                <>
                  <CloudOff className="h-4 w-4 text-slate-400" />
                  <span>Auto-save enabled</span>
                </>
              )}
            </div>
            {hasDraft && (
              <div className="flex items-center gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => {
                    const restored = restoreDraft();
                    if (restored) {
                      if (restored.imagePreview && restored.imagePreview.startsWith('data:')) {
                        setFormData(restored);
                      } else {
                        setFormData({ ...restored, imageFile: null, imagePreview: null });
                      }
                      showToast('Draft restored successfully', 'success');
                    }
                  }}
                  className="text-xs"
                >
                  <Cloud className="h-3 w-3 mr-1" />
                  Restore Draft
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => {
                    if (window.confirm('Are you sure you want to delete this draft? This action cannot be undone.')) {
                      clearDraft();
                      showToast('Draft deleted', 'info');
                    }
                  }}
                  className="text-xs text-red-600 hover:text-red-700 hover:bg-red-50"
                >
                  Delete Draft
                </Button>
              </div>
            )}
          </div>
        )}
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button
              variant="ghost"
              onClick={() => navigate('/cms/current-affairs')}
              className="hover:bg-slate-100"
            >
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Current Affairs
            </Button>
            <div>
              <h1 className="text-3xl font-bold text-slate-900">
                {isEditMode ? 'Edit Current Affair' : 'Create Current Affair'}
              </h1>
              <p className="text-slate-600 mt-1">
                {isEditMode ? 'Update current affair details' : 'Add a new current affair article'}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <Button
              onClick={handlePublish}
              disabled={createMutation.isPending || updateMutation.isPending || !isDescriptionValid}
              className="bg-gradient-to-r from-emerald-600 to-green-600 hover:from-emerald-700 hover:to-green-700 text-white font-semibold shadow-lg"
            >
              {(createMutation.isPending || updateMutation.isPending) ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Publishing...
                </>
              ) : (
                <>
                  <Send className="h-4 w-4 mr-2" />
                  Publish Article
                </>
              )}
            </Button>
          </div>
        </div>

        {/* Main Content - Full Width Form */}
        <Card className="border-0 shadow-xl bg-white">
            <CardHeader className="border-b border-slate-200 bg-gradient-to-r from-blue-50/50 to-white">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-xl bg-gradient-to-br from-blue-500 to-blue-600 shadow-md">
                  <Newspaper className="h-5 w-5 text-white" />
                </div>
                <div>
                  <CardTitle className="text-lg font-bold text-slate-900">Article Details</CardTitle>
                  <CardDescription className="text-slate-600">Enter current affair information</CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent className="pt-6 space-y-8">
              {/* Section 1: Category and Basic Information */}
              <div className="space-y-4 pb-6 border-b border-slate-200">
                <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
                  <Tag className="h-5 w-5 text-blue-600" />
                  Category and Basic Information
                </h3>
                
                {/* Category Fields - 3 Rows Layout */}
                <div className="grid grid-cols-3 gap-4">
                  <div className="space-y-2">
                    <label className="text-sm font-semibold text-slate-700">Category *</label>
                    <select
                      value={formData.categoryId}
                      onChange={(e) => handleCategoryChange(e.target.value)}
                      className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                    >
                      <option value="">Select Category</option>
                      {categories.map((cat: any) => (
                        <option key={cat.id} value={cat.id}>
                          {cat.name}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div className="space-y-2">
                    <label className="text-sm font-semibold text-slate-700">Sub Category</label>
                    <select
                      value={formData.subCategoryId}
                      onChange={(e) => {
                        const value = e.target.value;
                        const selected = subCategories.find((sub: any) => sub.id === value);
                        setFormData({
                          ...formData,
                          subCategoryId: value,
                          subCategory: selected?.name || '',
                        });
                      }}
                      className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                      disabled={!formData.categoryId || subCategories.length === 0}
                    >
                      <option value="">Select Sub Category</option>
                      {subCategories.map((sub: any) => (
                        <option key={sub.id} value={sub.id}>
                          {sub.name}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div className="space-y-2">
                    <label className="text-sm font-semibold text-slate-700">Chapter</label>
                    <select
                      value={formData.chapterId}
                      onChange={(e) =>
                        setFormData({ ...formData, chapterId: e.target.value })
                      }
                      className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                      disabled={!formData.subCategoryId || chapters.length === 0}
                    >
                      <option value="">Select Chapter</option>
                      {chapters.map((chapter: Chapter) => (
                        <option key={chapter.id} value={chapter.id}>
                          {chapter.name}
                        </option>
                      ))}
                    </select>
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="text-sm font-semibold text-slate-700 mb-2 block">Title *</label>
                    <Input
                      placeholder="Enter article title"
                      value={formData.title}
                      onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                      className="mt-1"
                    />
                  </div>
                  <div className="bg-blue-50 p-4 rounded-lg border border-blue-200">
                    <label className="text-sm font-semibold text-slate-700 mb-2 block">Language *</label>
                    <select
                      value={formData.language || 'ENGLISH'}
                      onChange={(e) => setFormData({ ...formData, language: e.target.value })}
                      className="w-full px-3 py-2 border-2 border-blue-300 rounded-md text-sm font-medium bg-white focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    >
                      <option value="ENGLISH">English</option>
                      <option value="HINDI">Hindi (हिंदी)</option>
                    </select>
                    <p className="text-xs text-slate-600 mt-2 font-medium">Select the language of the article content</p>
                  </div>
                </div>

              </div>

              {/* Section 2: Date and Location Details */}
              <div className="space-y-4 pb-6 border-b border-slate-200">
                <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
                  <Calendar className="h-5 w-5 text-blue-600" />
                  Date and Location Details
                </h3>

                {/* Date Fields - 3 Rows Layout */}
                <div className="grid grid-cols-3 gap-4">
                  <div>
                    <label className="text-sm font-semibold text-slate-700 mb-2 block flex items-center gap-2">
                      Event Date
                    </label>
                    <Input
                      type="date"
                      value={formData.date}
                      onChange={(e) => setFormData({ ...formData, date: e.target.value })}
                      className="mt-1"
                    />
                  </div>
                  <div>
                    <label className="text-sm font-semibold text-slate-700 mb-2 block">
                      Event Year Range
                    </label>
                    <Input
                      placeholder="e.g., 2020-2024"
                      value={formData.eventYearRange}
                      onChange={(e) => setFormData({ ...formData, eventYearRange: e.target.value })}
                      className="mt-1"
                    />
                  </div>
                  <div className="col-span-3">
                    <label className="text-sm font-semibold text-slate-700 mb-2 block">
                      Notification Dates (Month & Day)
                    </label>
                    <div className="space-y-3">
                      {formData.eventDates.length === 0 ? (
                        <Button
                          type="button"
                          variant="outline"
                          size="sm"
                          onClick={() => {
                            setFormData({ ...formData, eventDates: [{ date: '', title: '' }] });
                          }}
                          className="w-full"
                        >
                          <Plus className="h-4 w-4 mr-2" />
                          Add Notification Date
                        </Button>
                      ) : (
                        <>
                          {formData.eventDates.map((notification, index) => (
                            <div key={index} className="space-y-2 p-3 border border-slate-200 rounded-lg bg-slate-50">
                              <div className="flex items-center gap-2">
                              <Input
                                type="text"
                                  value={notification.date}
                                onChange={(e) => {
                                  const newDates = [...formData.eventDates];
                                    newDates[index] = { ...newDates[index], date: e.target.value };
                                  setFormData({ ...formData, eventDates: newDates });
                                }}
                                className="flex-1"
                                placeholder="MM-DD"
                              />
                              <Button
                                type="button"
                                variant="outline"
                                size="sm"
                                onClick={() => {
                                  const newDates = formData.eventDates.filter((_, i) => i !== index);
                                  setFormData({ ...formData, eventDates: newDates });
                                }}
                                disabled={formData.eventDates.length === 1}
                              >
                                <X className="h-4 w-4" />
                              </Button>
                              </div>
                              <Input
                                type="text"
                                value={notification.title}
                                onChange={(e) => {
                                  const newDates = [...formData.eventDates];
                                  newDates[index] = { ...newDates[index], title: e.target.value };
                                  setFormData({ ...formData, eventDates: newDates });
                                }}
                                className="w-full"
                                placeholder="Notification title (e.g., Republic Day Reminder)"
                              />
                            </div>
                          ))}
                          <Button
                            type="button"
                            variant="outline"
                            size="sm"
                            onClick={() => {
                              setFormData({ ...formData, eventDates: [...formData.eventDates, { date: '', title: '' }] });
                            }}
                            className="w-full"
                          >
                            <Plus className="h-4 w-4 mr-2" />
                            Add Another Notification Date
                          </Button>
                        </>
                      )}
                    </div>
                    <p className="text-xs text-slate-500 mt-2">
                      Notifications will be sent automatically on these dates each year (use MM-DD format). Include a title for each notification.
                    </p>
                  </div>
                </div>

                {/* Location Section - 3 Rows Layout */}
                <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
                  <label className="text-sm font-semibold text-slate-700 mb-3 block flex items-center gap-2">
                    <MapPin className="h-4 w-4" />
                    Location
                  </label>
                  
                  {/* Row 1: Longitude, Latitude, Country */}
                  <div className="grid grid-cols-3 gap-3 mb-4">
                    <div>
                      <label className="text-xs text-slate-600 mb-1 block">Longitude</label>
                      <Input
                        type="number"
                        step="any"
                        placeholder="e.g., 77.2090"
                        value={formData.location.long}
                        onChange={(e) => setFormData({
                          ...formData,
                          location: { ...formData.location, long: e.target.value }
                        })}
                        className="mt-1"
                      />
                    </div>
                    <div>
                      <label className="text-xs text-slate-600 mb-1 block">Latitude</label>
                      <Input
                        type="number"
                        step="any"
                        placeholder="e.g., 28.6139"
                        value={formData.location.lat}
                        onChange={(e) => setFormData({
                          ...formData,
                          location: { ...formData.location, lat: e.target.value }
                        })}
                        className="mt-1"
                      />
                    </div>
                    <div>
                      <label className="text-xs text-slate-600 mb-1 block">Country *</label>
                      <Input
                        placeholder="Enter country"
                        value={formData.country}
                        onChange={(e) => setFormData({ ...formData, country: e.target.value })}
                        className="mt-1"
                      />
                    </div>
                  </div>

                  {/* Row 2: State, District, City */}
                  <div className="grid grid-cols-3 gap-3">
                    <div>
                      <label className="text-xs text-slate-600 mb-1 block">State</label>
                      <Input
                        placeholder="Enter state"
                        value={formData.state}
                        onChange={(e) => setFormData({ ...formData, state: e.target.value })}
                        className="mt-1"
                      />
                    </div>
                    <div>
                      <label className="text-xs text-slate-600 mb-1 block">District</label>
                      <Input
                        placeholder="Enter district"
                        value={formData.district}
                        onChange={(e) => setFormData({ ...formData, district: e.target.value })}
                        className="mt-1"
                      />
                    </div>
                    <div>
                      <label className="text-xs text-slate-600 mb-1 block">City</label>
                      <Input
                        placeholder="Enter city"
                        value={formData.city}
                        onChange={(e) => setFormData({ ...formData, city: e.target.value })}
                        className="mt-1"
                      />
                    </div>
                  </div>
                </div>
              </div>

              {/* Section 3: Content */}
              <div className="space-y-4">
                <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
                  <Newspaper className="h-5 w-5 text-blue-600" />
                  Content
                </h3>

                {/* Image Upload */}
                <div>
                  <label className="text-sm font-semibold text-slate-700 mb-2 block flex items-center gap-2">
                    <ImageIcon className="h-4 w-4" />
                    Image Upload
                  </label>
                
                {formData.imagePreview || formData.imageUrl ? (
                  <div className="mt-2 space-y-3">
                    <div className="relative">
                      <img
                        src={formData.imagePreview || formData.imageUrl}
                        alt="Article preview"
                        className="w-full max-w-md h-48 object-cover rounded-lg border-2 border-slate-200 bg-slate-50"
                        onError={(e) => {
                          (e.target as HTMLImageElement).style.display = 'none';
                        }}
                      />
                      <button
                        type="button"
                        onClick={removeImage}
                        className="absolute top-2 right-2 p-2 bg-red-500 text-white rounded-full hover:bg-red-600 transition-colors shadow-lg"
                      >
                        <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                      </button>
                    </div>
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() => document.getElementById('image-upload')?.click()}
                      className="flex-1"
                    >
                      <ImageIcon className="h-4 w-4 mr-2" />
                      Change Image
                    </Button>
                  </div>
                ) : (
                  <div className="mt-2">
                    <input
                      type="file"
                      id="image-upload"
                      accept="image/*"
                      onChange={handleImageUpload}
                      className="hidden"
                    />
                    <label htmlFor="image-upload">
                      <div className="border-2 border-dashed border-slate-300 rounded-xl p-6 text-center hover:border-blue-400 transition-colors cursor-pointer bg-slate-50 hover:bg-blue-50/50">
                        <div className="flex flex-col items-center gap-3">
                          <div className="p-3 rounded-full bg-blue-100">
                            <ImageIcon className="h-6 w-6 text-blue-600" />
                          </div>
                          <div>
                            <p className="text-sm font-semibold text-slate-900 mb-1">Click to upload image</p>
                            <p className="text-xs text-slate-500">PNG, JPG, GIF up to 5MB</p>
                          </div>
                        </div>
                      </div>
                    </label>
                  </div>
                )}

                {/* Alternative: Image URL */}
                <div className="mt-4 pt-4 border-t border-slate-200">
                  <details className="group">
                    <summary className="text-xs font-medium text-slate-600 cursor-pointer hover:text-slate-900">
                      Or use image URL instead
                    </summary>
                    <div className="mt-2">
                      <Input
                        placeholder="https://example.com/image.jpg"
                        value={formData.imageUrl}
                        onChange={(e) => {
                          if (e.target.value) {
                            setFormData({ 
                              ...formData, 
                              imageUrl: e.target.value,
                              imageFile: null,
                              imagePreview: null,
                            });
                          }
                        }}
                        className="mt-1"
                        disabled={!!formData.imagePreview}
                      />
                    </div>
                  </details>
                </div>
                </div>

                {/* Description */}
                <div>
                  <label className="text-sm font-semibold text-slate-700 mb-2 block">
                    Description *
                  </label>
                  <RichTextEditor
                    key={`description-${dataLoadedKey}`}
                    value={formData.description}
                    onChange={(value) => {
                      setFormData({ ...formData, description: value });
                    }}
                    placeholder="Write a brief description with full formatting options..."
                    minHeight="60px"
                    className="mt-1 description-editor"
                  />
                  <div className="mt-2 flex items-center justify-between">
                    <p className={`text-xs ${isDescriptionValid ? 'text-emerald-600' : 'text-slate-600'}`}>
                      {descriptionWordCount} words (no limit)
                    </p>
                    {isDescriptionValid && (
                      <span className="text-xs text-emerald-600 font-semibold">✓ Valid</span>
                    )}
                  </div>
                </div>

                {/* Full Article */}
                <div>
                  <label className="text-sm font-semibold text-slate-700 mb-2 block">Full Article</label>
                  <RichTextEditor
                    key={`fullArticle-${dataLoadedKey}`}
                    value={formData.fullArticle}
                    onChange={(value) => setFormData({ ...formData, fullArticle: value })}
                    placeholder="Write the complete article content with full formatting options..."
                    minHeight="400px"
                    className="mt-1"
                  />
                  <p className="text-xs text-slate-500 mt-2">
                    This is the complete article content. Use the toolbar above to format your text (bold, italic, underline, alignment, links, etc.). The description above is a brief summary.
                  </p>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="space-y-4 pt-4 border-t border-slate-200 mt-6">
                <div className="flex items-center gap-2">
                  <Button
                    type="button"
                    variant="outline"
                    onClick={handleOpenMcqDialog}
                    className="flex-1"
                  >
                    <HelpCircle className="h-4 w-4 mr-2" />
                    Create MCQ
                  </Button>
                </div>

                <div className="space-y-2">
                  <div className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      id="sendNotification-ca"
                      checked={formData.sendNotification}
                      onChange={(e) => setFormData({ ...formData, sendNotification: e.target.checked })}
                      className="h-4 w-4 text-blue-600 rounded"
                    />
                    <label htmlFor="sendNotification-ca" className="text-sm font-medium text-slate-700 cursor-pointer">
                      Send Notification
                    </label>
                  </div>
                  {formData.sendNotification && (
                    <div>
                      <label className="text-xs text-slate-600 mb-1 block">Select clock time else current time</label>
                      <Input
                        type="time"
                        value={formData.notificationTime}
                        onChange={(e) => setFormData({ ...formData, notificationTime: e.target.value })}
                        className="w-full"
                      />
                    </div>
                  )}
                </div>
              </div>
            </CardContent>
          </Card>

        {/* Preview Section - Bottom, Side by Side */}
        <Card className="border-0 shadow-xl bg-white mt-6">
          <CardHeader className="border-b border-slate-200 bg-gradient-to-r from-emerald-50/50 to-white">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-xl bg-gradient-to-br from-emerald-500 to-emerald-600 shadow-md">
                <Eye className="h-5 w-5 text-white" />
              </div>
              <div>
                <CardTitle className="text-lg font-bold text-slate-900">Live Preview</CardTitle>
                <CardDescription className="text-slate-600">See how your article will appear</CardDescription>
              </div>
            </div>
          </CardHeader>
          <CardContent className="pt-6">
            <div className="grid grid-cols-2 gap-6">
              {/* Post Preview */}
              <div>
                <h4 className="text-sm font-semibold text-slate-700 mb-3">Post Preview</h4>
                <div className="bg-gradient-to-br from-slate-50 to-slate-100 rounded-xl p-4 border-2 border-dashed border-slate-300 min-h-[300px]">
                  <div className="bg-white rounded-lg shadow-md overflow-hidden border border-slate-200">
                    {/* Image Preview */}
                    {(formData.imagePreview || formData.imageUrl) && (
                      <div className="w-full h-48 bg-slate-100 overflow-hidden">
                        <img
                          src={formData.imagePreview || formData.imageUrl}
                          alt="Article"
                          className="w-full h-full object-cover"
                          onError={(e) => {
                            (e.target as HTMLImageElement).style.display = 'none';
                          }}
                        />
                      </div>
                    )}
                    {/* Title */}
                    <div className="p-4">
                      {formData.title ? (
                        <h3 className="text-xl font-bold text-slate-900 mb-3">{formData.title}</h3>
                      ) : (
                        <div className="h-6 bg-slate-200 rounded animate-pulse mb-3"></div>
                      )}
                      {/* Description */}
                      {formData.description ? (
                        <div 
                          className="text-sm text-slate-600 article-preview-content line-clamp-4"
                          style={{ 
                            overflow: 'hidden',
                            display: '-webkit-box',
                            WebkitLineClamp: 4,
                            WebkitBoxOrient: 'vertical'
                          }}
                          dangerouslySetInnerHTML={{ __html: formData.description }}
                        />
                      ) : (
                        <div className="space-y-2">
                          <div className="h-4 bg-slate-200 rounded animate-pulse"></div>
                          <div className="h-4 bg-slate-200 rounded animate-pulse w-5/6"></div>
                          <div className="h-4 bg-slate-200 rounded animate-pulse w-4/6"></div>
                        </div>
                      )}
                      {/* Post Meta */}
                      <div className="pt-3 mt-3 border-t border-slate-200">
                        <div className="flex items-center gap-2 text-xs text-slate-500">
                          <Newspaper className="h-3 w-3" />
                          <span>Current Affairs</span>
                          <span>•</span>
                          <span>{new Date().toLocaleDateString()}</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Full Article Preview */}
              <div>
                <h4 className="text-sm font-semibold text-slate-700 mb-3">Full Article Preview</h4>
                <div className="bg-gradient-to-br from-slate-50 to-slate-100 rounded-xl p-4 border-2 border-dashed border-slate-300 min-h-[300px]">
                  {formData.fullArticle ? (
                    <div 
                      className="text-sm text-slate-700 article-preview-content bg-white p-4 rounded-lg max-h-[400px] overflow-y-auto"
                      dangerouslySetInnerHTML={{ __html: formData.fullArticle }}
                    />
                  ) : (
                    <div className="space-y-2 p-4">
                      <div className="h-4 bg-slate-200 rounded animate-pulse"></div>
                      <div className="h-4 bg-slate-200 rounded animate-pulse w-5/6"></div>
                      <div className="h-4 bg-slate-200 rounded animate-pulse w-4/6"></div>
                      <div className="h-4 bg-slate-200 rounded animate-pulse w-5/6"></div>
                      <div className="h-4 bg-slate-200 rounded animate-pulse w-3/6"></div>
                    </div>
                  )}
                </div>
              </div>
            </div>
            
            {/* Publish Button in Preview */}
            <div className="mt-6 pt-6 border-t border-slate-200">
              <Button
                onClick={handlePublish}
                disabled={createMutation.isPending || updateMutation.isPending || !isDescriptionValid}
                className="w-full bg-gradient-to-r from-emerald-600 to-green-600 hover:from-emerald-700 hover:to-green-700 text-white font-semibold shadow-lg"
              >
                {(createMutation.isPending || updateMutation.isPending) ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Publishing...
                  </>
                ) : (
                  <>
                    <Send className="h-4 w-4 mr-2" />
                    Publish Article
                  </>
                )}
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Category creation removed - use Wall Categories in dashboard instead */}

      {/* Create MCQ Dialog */}
      <Dialog open={isMcqDialogOpen} onOpenChange={setIsMcqDialogOpen}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center justify-between">
              <span>Create MCQ Questions</span>
              <Button
                variant="ghost"
                size="sm"
                onClick={handleCloseMcqDialog}
                className="h-6 w-6 p-0"
              >
                <X className="h-4 w-4" />
              </Button>
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-6">
            {/* Warning if article not created */}
            {!formData.articleId && !id && (
              <div className="p-3 rounded-lg bg-yellow-50 border border-yellow-200">
                <p className="text-sm text-yellow-800">
                  <strong>Note:</strong> The article hasn't been created yet. MCQs will be created without an article link. Create the article first to automatically link them.
                </p>
              </div>
            )}
            {/* Created MCQs List */}
            {createdMcqs.length > 0 && (
              <div className="border border-slate-200 rounded-lg p-4 bg-slate-50">
                <h3 className="text-sm font-semibold text-slate-700 mb-3">
                  Created MCQs ({createdMcqs.length})
                </h3>
                <div className="space-y-2 max-h-40 overflow-y-auto">
                  {createdMcqs.map((mcq, idx) => (
                    <div key={mcq.id || idx} className="flex items-center justify-between p-2 bg-white rounded border border-slate-200">
                      <div className="flex-1">
                        <p className="text-sm font-medium text-slate-900 line-clamp-1">
                          {mcq.question || `MCQ ${idx + 1}`}
                        </p>
                      </div>
                      <CheckCircle2 className="h-4 w-4 text-emerald-600 ml-2" />
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* MCQ Form */}
            <div className="space-y-4">
              {/* Category and Basic Information */}
              <div className="grid grid-cols-3 gap-4">
                {/* Category */}
                <div>
                  <label className="text-sm font-semibold text-slate-700 mb-2 block">Category</label>
                  <select
                    value={mcqFormData.categoryId}
                    onChange={(e) => setMcqFormData({ 
                      ...mcqFormData, 
                      categoryId: e.target.value,
                      subCategoryId: '', // Reset sub-category when category changes
                      chapterId: '', // Reset chapter when category changes
                    })}
                    className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                  >
                    <option value="">Select a category</option>
                    {categories.map((cat: any) => (
                      <option key={cat.id} value={cat.id}>
                        {cat.name}
                      </option>
                    ))}
                  </select>
                </div>

                {/* Sub Category */}
                <div>
                  <label className="text-sm font-semibold text-slate-700 mb-2 block">Sub Category</label>
                  <select
                    value={mcqFormData.subCategoryId}
                    onChange={(e) => setMcqFormData({ 
                      ...mcqFormData, 
                      subCategoryId: e.target.value,
                      chapterId: '', // Reset chapter when sub-category changes
                    })}
                    disabled={!mcqFormData.categoryId}
                    className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white disabled:bg-slate-100 disabled:cursor-not-allowed"
                  >
                    <option value="">Select a sub-category</option>
                    {mcqSubCategories.map((subCat: any) => (
                      <option key={subCat.id} value={subCat.id}>
                        {subCat.name}
                      </option>
                    ))}
                  </select>
                </div>

                {/* Chapter */}
                <div>
                  <label className="text-sm font-semibold text-slate-700 mb-2 block">Chapter</label>
                  <select
                    value={mcqFormData.chapterId}
                    onChange={(e) => setMcqFormData({ ...mcqFormData, chapterId: e.target.value })}
                    disabled={!mcqFormData.subCategoryId}
                    className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white disabled:bg-slate-100 disabled:cursor-not-allowed"
                  >
                    <option value="">Select a chapter</option>
                    {mcqChapters.map((chapter: Chapter) => (
                      <option key={chapter.id} value={chapter.id}>
                        {chapter.name}
                      </option>
                    ))}
                  </select>
                </div>
              </div>

              {/* Question */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">Question *</label>
                <Textarea
                  placeholder="Enter the question..."
                  value={mcqFormData.question}
                  onChange={(e) => setMcqFormData({ ...mcqFormData, question: e.target.value })}
                  className="min-h-[100px]"
                  rows={4}
                />
              </div>

              {/* Options */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">Answer Options *</label>
                <div className="space-y-3">
                  {mcqFormData.options.map((option, index) => (
                    <div key={index} className="flex items-center gap-3">
                      <div className={`flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center font-bold text-sm ${
                        mcqFormData.correctAnswer === index
                          ? 'bg-emerald-500 text-white'
                          : 'bg-slate-200 text-slate-600'
                      }`}>
                        {String.fromCharCode(65 + index)}
                      </div>
                      <Input
                        placeholder={`Option ${String.fromCharCode(65 + index)}`}
                        value={option}
                        onChange={(e) => updateMcqOption(index, e.target.value)}
                        className="flex-1"
                      />
                      <Button
                        type="button"
                        variant={mcqFormData.correctAnswer === index ? 'default' : 'outline'}
                        size="sm"
                        onClick={() => setMcqFormData({ ...mcqFormData, correctAnswer: index })}
                        className={mcqFormData.correctAnswer === index ? 'bg-emerald-600 hover:bg-emerald-700' : ''}
                      >
                        {mcqFormData.correctAnswer === index ? (
                          <CheckCircle2 className="h-4 w-4" />
                        ) : (
                          <XCircle className="h-4 w-4" />
                        )}
                      </Button>
                    </div>
                  ))}
                </div>
                <p className="text-xs text-slate-500 mt-2">Click the checkmark to mark the correct answer</p>
              </div>

              {/* Explanation */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">Explanation (Optional)</label>
                <Textarea
                  placeholder="Explain why this is the correct answer..."
                  value={mcqFormData.explanation}
                  onChange={(e) => setMcqFormData({ ...mcqFormData, explanation: e.target.value })}
                  className="min-h-[80px]"
                  rows={4}
                />
                
                {/* Explanation Image Upload */}
                <div className="mt-4">
                  <label className="text-sm font-semibold text-slate-700 mb-2 block">Explanation Image (Optional)</label>
                  {mcqFormData.explanationImagePreview ? (
                    <div className="relative inline-block">
                      <img
                        src={mcqFormData.explanationImagePreview}
                        alt="Explanation preview"
                        className="max-w-full h-auto max-h-64 rounded-lg border border-slate-300"
                      />
                      <Button
                        type="button"
                        variant="destructive"
                        size="sm"
                        onClick={removeMcqExplanationImage}
                        className="absolute top-2 right-2"
                      >
                        <X className="h-4 w-4" />
                      </Button>
                    </div>
                  ) : (
                    <div className="border-2 border-dashed border-slate-300 rounded-lg p-6 text-center hover:border-blue-400 transition-colors">
                      <input
                        type="file"
                        accept="image/*"
                        onChange={handleMcqExplanationImageUpload}
                        className="hidden"
                        id="mcq-explanation-image-upload"
                      />
                      <label
                        htmlFor="mcq-explanation-image-upload"
                        className="cursor-pointer flex flex-col items-center gap-2"
                      >
                        <ImageIcon className="h-8 w-8 text-slate-400" />
                        <span className="text-sm text-slate-600">
                          Click to upload an image or drag and drop
                        </span>
                        <span className="text-xs text-slate-500">PNG, JPG, GIF up to 5MB</span>
                      </label>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
          <DialogFooter className="flex items-center justify-end">
            <Button
              onClick={handleCreateMcq}
              disabled={createMcqMutation.isPending}
              className="bg-gradient-to-r from-emerald-600 to-green-600 hover:from-emerald-700 hover:to-green-700 text-white font-semibold shadow-lg"
            >
              {createMcqMutation.isPending ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Publishing...
                </>
              ) : (
                <>
                  <Send className="h-4 w-4 mr-2" />
                  Publish
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
      </AdminLayout>
    </>
  );
}

